#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// Util.cpp

T_("Aborted by user.")
csCZ("Operace byla přerušena uživatelem.")
deDE("Vom Benutzer abgebrochen")
frFR("Annulé par l'utilisateur.")
huHU("Megszakította a felhasználó")
itIT("Annullato dall'utente")
plPL("Anulowany przez użytkownika")
ruRU("Прервано пользователем")
srSP("Prekinuto od strane korisnika.")
trTR("Kullanıcı tarafından iptal edildi.")
zhCN("用户放弃")


// TimeDate.cpp

T_("date\vSunday")
csCZ("Neděle")
deDE("Sonntag")
frFR("Dimanche")
huHU("Vasárnap")
itIT("Domenica")
plPL("Niedziela")
ruRU("Суббота")
srSP("Nedelja")
trTR("Pazar")
zhCN("星期日")

T_("date\vMonday")
csCZ("Pondělí")
deDE("Montag")
frFR("Lundi")
huHU("Hétfő")
itIT("Lunedì")
plPL("Poniedziałek")
ruRU("Понедельник")
srSP("Ponedeljak")
trTR("Pazartesi")
zhCN("星期一")

T_("date\vTuesday")
csCZ("Úterý")
deDE("Dienstag")
frFR("Mardi")
huHU("Kedd")
itIT("Martedì")
plPL("Wtorek")
ruRU("Вторник")
srSP("Utorak")
trTR("Salı")
zhCN("星期二")

T_("date\vWednesday")
csCZ("Středa")
deDE("Mittwoch")
frFR("Mercredi")
huHU("Szerda")
itIT("Mercoledì")
plPL("Środa")
ruRU("Среда")
srSP("Sreda")
trTR("Çarşamba")
zhCN("星期三")

T_("date\vThursday")
csCZ("Čtvrtek")
deDE("Donnerstag")
frFR("Jeudi")
huHU("Csütörtök")
itIT("Giovedì")
plPL("Czwartek")
ruRU("Четверг")
srSP("Četvrtak")
trTR("Perşembe")
zhCN("星期四")

T_("date\vFriday")
csCZ("Pátek")
deDE("Freitag")
frFR("Vendredi")
huHU("Péntek")
itIT("Venerdì")
plPL("Piątek")
ruRU("Пятница")
srSP("Petak")
trTR("Cuma")
zhCN("星期五")

T_("date\vSaturday")
csCZ("Sobota")
deDE("Samstag")
frFR("Samedi")
huHU("Szombat")
itIT("Sabato")
plPL("Sobota")
ruRU("Воскресенье")
srSP("Subota")
trTR("Cumartesi")
zhCN("星期六")

T_("date\vSu")
csCZ("Ne")
deDE("Sa")
frFR("Sam")
huHU("Szo")
itIT("Do")
plPL("So")
ruRU("Вс")
srSP("Ne")
trTR("Pz")
zhCN("Fri")

T_("date\vMo")
csCZ("Po")
deDE("Mo")
frFR("Lun")
huHU("Hé")
itIT("Lu")
plPL("Po")
ruRU("Пн")
srSP("Po")
trTR("Pts")
zhCN("Mon")

T_("date\vTu")
csCZ("Út")
deDE("Di")
frFR("Mar")
huHU("Ke")
itIT("Ma")
plPL("Wt")
ruRU("Вт")
srSP("Ut")
trTR("Sl")
zhCN("Tue")

T_("date\vWe")
csCZ("St")
deDE("Mi")
frFR("Mer")
huHU("Sze")
itIT("Me")
plPL("Śr")
ruRU("Ср")
srSP("Sr")
trTR("Çrş")
zhCN("Wed")

T_("date\vTh")
csCZ("Čt")
deDE("Do")
frFR("Jeu")
huHU("Csüt")
itIT("Gi")
plPL("Cz")
ruRU("Чт")
srSP("Če")
trTR("Prş")
zhCN("Thu")

T_("date\vFr")
csCZ("Pa")
deDE("Fr")
frFR("Ven")
huHU("Pé")
itIT("Ve")
plPL("Pt")
ruRU("Пт")
srSP("Pe")
trTR("Cu")
zhCN("")

T_("date\vSa")
csCZ("So")
deDE("So")
frFR("Dim")
huHU("Vas")
itIT("Sa")
plPL("Nd")
ruRU("Сб")
srSP("Su")
trTR("Cts")
zhCN("Sun")

T_("date\vJanuary")
csCZ("Leden")
deDE("Januar")
frFR("Janvier")
huHU("Január")
itIT("Gennaio")
plPL("Styczeń")
ruRU("Январь")
srSP("Januar")
trTR("Ocak")
zhCN("一月")

T_("date\vFebruary")
csCZ("Únor")
deDE("Februar")
frFR("Février")
huHU("Február")
itIT("Febbraio")
plPL("Luty")
ruRU("Февраль")
srSP("Februar")
trTR("Şubat")
zhCN("二月")

T_("date\vMarch")
csCZ("Březen")
deDE("März")
frFR("Mars")
huHU("Március")
itIT("Marzo")
plPL("Marzec")
ruRU("Март")
srSP("Mart")
trTR("Mart")
zhCN("三月")

T_("date\vApril")
csCZ("Duben")
deDE("April")
frFR("Avril")
huHU("Április")
itIT("Aprile")
plPL("Kwiecień")
ruRU("Апрель")
srSP("April")
trTR("Nisan")
zhCN("四月")

T_("date\vMay")
csCZ("Květen")
deDE("Mai")
frFR("Mai")
huHU("Május")
itIT("Maggio")
plPL("Maj")
ruRU("Май")
srSP("Maj")
trTR("Mayıs")
zhCN("五月")

T_("date\vJune")
csCZ("Červen")
deDE("Juni")
frFR("Juin")
huHU("Június")
itIT("Giugno")
plPL("Czerwiec")
ruRU("Июнь")
srSP("Jun")
trTR("Haziran")
zhCN("六月")

T_("date\vJuly")
csCZ("Červenec")
deDE("Juli")
frFR("Juillet")
huHU("Július")
itIT("Luglio")
plPL("Lipiec")
ruRU("Июль")
srSP("Jul")
trTR("Temmuz")
zhCN("七月")

T_("date\vAugust")
csCZ("Srpen")
deDE("August")
frFR("Août")
huHU("Augusztus")
itIT("Agosto")
plPL("Sierpień")
ruRU("Август")
srSP("Avgust")
trTR("Ağustos")
zhCN("八月")

T_("date\vSeptember")
csCZ("Září")
deDE("September")
frFR("Septembre")
huHU("Szeptember")
itIT("Settembre")
plPL("Wrzesień")
ruRU("Сентябрь")
srSP("Septembar")
trTR("Eylül")
zhCN("九月")

T_("date\vOctober")
csCZ("Říjen")
deDE("Oktober")
frFR("Octobre")
huHU("Október")
itIT("Ottobre")
plPL("Październik")
ruRU("Октябрь")
srSP("Oktobar")
trTR("Ekim")
zhCN("十月")

T_("date\vNovember")
csCZ("Listopad")
deDE("November")
frFR("Novembre")
huHU("November")
itIT("Novembre")
plPL("Listopad")
ruRU("Ноябрь")
srSP("Novembar")
trTR("Kasım")
zhCN("十一月")

T_("date\vDecember")
csCZ("Prosinec")
deDE("Dezember")
frFR("Décembre")
huHU("December")
itIT("Dicembre")
plPL("Grudzień")
ruRU("Декабрь")
srSP("Decembar")
trTR("Aralık")
zhCN("十二月")

T_("sdate\vJan")
csCZ("Led")
deDE("Jan")
frFR("Jan")
huHU("Jan")
itIT("Gen")
plPL("Sty")
ruRU("Янв")
srSP("Jan")
trTR("Ock")
zhCN("Jan")

T_("sdate\vFeb")
csCZ("Úno")
deDE("Feb")
frFR("Fév")
huHU("Feb")
itIT("Feb")
plPL("Lut")
ruRU("Фев")
srSP("Feb")
trTR("Şub")
zhCN("Feb")

T_("sdate\vMar")
csCZ("Bře")
deDE("Mär")
frFR("Mar")
huHU("Márc")
itIT("Mar")
plPL("Mar")
ruRU("Мрт")
srSP("Mar")
trTR("Mar")
zhCN("Mar")

T_("sdate\vApr")
csCZ("Dub")
deDE("Apr")
frFR("Avr")
huHU("Ápr")
itIT("Apr")
plPL("Kwi")
ruRU("Апр")
srSP("Apr")
trTR("Nis")
zhCN("Apr")

T_("sdate\vMay")
csCZ("Kvě")
deDE("Mai")
frFR("Mai")
huHU("Máj")
itIT("Mag")
plPL("Maj")
ruRU("Май")
srSP("Maj")
trTR("May")
zhCN("May")

T_("sdate\vJun")
csCZ("Čer")
deDE("Jun")
frFR("Jun")
huHU("Jún")
itIT("Giu")
plPL("Cze")
ruRU("Инь")
srSP("Jun")
trTR("Haz")
zhCN("Jun")

T_("sdate\vJul")
csCZ("Čec")
deDE("Jul")
frFR("Jui")
huHU("Júl")
itIT("Lug")
plPL("Lip")
ruRU("Иль")
srSP("Jul")
trTR("Tem")
zhCN("Jul")

T_("sdate\vAug")
csCZ("Srp")
deDE("Aug")
frFR("Aou")
huHU("Aug")
itIT("Ago")
plPL("Sie")
ruRU("Авг")
srSP("Avg")
trTR("Ağu")
zhCN("Aug")

T_("sdate\vSep")
csCZ("Zář")
deDE("Sep")
frFR("Sep")
huHU("Szept")
itIT("Set")
plPL("Wrz")
ruRU("Сен")
srSP("Sep")
trTR("Eyl")
zhCN("Sep")

T_("sdate\vOct")
csCZ("Říj")
deDE("Okt")
frFR("Oct")
huHU("Okt")
itIT("Ott")
plPL("Paź")
ruRU("Окт")
srSP("Okt")
trTR("Ekm")
zhCN("Oct")

T_("sdate\vNov")
csCZ("Lis")
deDE("Nov")
frFR("Nov")
huHU("Nov")
itIT("Nov")
plPL("Lis")
ruRU("Ноя")
srSP("Nov")
trTR("Kas")
zhCN("Nov")

T_("sdate\vDec")
csCZ("Pro")
deDE("Dez")
frFR("Déc")
huHU("Dec")
itIT("Dic")
plPL("Gru")
ruRU("Дек")
srSP("Dec")
trTR("Arl")
zhCN("Dec")


// Convert.cpp

T_("Invalid number !")
csCZ("Chybný zápis čísla !")
deDE("Ungültige Zahl!")
frFR("Nombre invalide !")
huHU("Érvénytelen szám")
itIT("Numero non valido !")
plPL("Niepoprawny numer !")
ruRU("Неправильное число!")
srSP("Pogrešan broj!")
trTR("Geçersiz sayı !")
zhCN("无效数字!")

T_("Invalid date !")
csCZ("Chybný zápis data !")
deDE("Ungültiges Datum!")
frFR("Date invalide !")
huHU("Érvénytelen dátum")
itIT("Data non valida !")
plPL("Niepoprawna data !")
ruRU("Неправильная дата!")
srSP("Pogrešan datum!")
trTR("Geçersiz tarih !")
zhCN("无效日期")

T_("Invalid time !")
csCZ("")
deDE("")
frFR("")
huHU("Érvénytelen időpont")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Geçersiz Zaman !")
zhCN("")

T_("Null value not allowed.")
csCZ("Hodnota nesmí být prázdná.")
deDE("Null nicht erlaubt.")
frFR("Valeur nulle non autorisée.")
huHU("Nullérték nem megengedett")
itIT("Lo zero non è ammesso")
plPL("Pusta wartość jest niedozwolona.")
ruRU("Нулевое значение не разрешено.")
srSP("Bez vrednosti nisu dopuštene.")
trTR("Bu alan boş bırakılamaz.")
zhCN("不允许空值.")

T_("Number must be between %d and %d.")
csCZ("Číslo musí být v rozsahu %d až %d.")
deDE("Zahl muss zwischen %d und %d liegen.")
frFR("Le nombre doit être compris entre %d et %d.")
huHU("A számnak %d és %d közé kell esnie")
itIT("Il numero deve essere compreso tra %d e %d.")
plPL("Numer musi być z przedziału %d i %d.")
ruRU("Число должно быть в пределах между %d и "
     "%d")
srSP("Broj mora biti između %d i %d.")
trTR("Girilen sayı %d ile %d aralığında olmaldır.")
zhCN("数字必须在%d和%d之间.")

T_("Number must be between %g and %g.")
csCZ("Číslo musí být v rozsahu %g až %g.")
deDE("Zahl muss zwischen %g und %g liegen.")
frFR("Le nombre doit être compris entre %g et %g.")
huHU("A számnak %g és %g közé kell esnie")
itIT("Il numero deve essere compreso tra %g e %g.")
plPL("Numer musi być z przedziału %g i %g.")
ruRU("Число должно быть в пределах между %g и "
     "%g")
srSP("Broj mora biti između %g i %g.")
trTR("Girilen sayı %g ile %g aralığında olmaldır.")
zhCN("数字必须在%g和%g之间.")

T_("Date must be between ")
csCZ("Datum musí být v rozsahu ")
deDE("Datum muss liegen zwischen ")
frFR("La date doit comprise entre")
huHU("A dátum érvényes határai ")
itIT("La data deve essere compre tra ")
plPL("Data musi być z zakresu ")
ruRU("Дата должна быть в пределах ")
srSP("Datum mora biti između ")
trTR("Girilen tarih")
zhCN("日期必须介入")

T_("range\v and ")
csCZ(" až ")
deDE("range\v und ")
frFR(" et ")
huHU(" és ")
itIT(" e ")
plPL(" i ")
ruRU(" и ")
srSP(" i ")
trTR(" and ")
zhCN(" 和 ")

T_("Time must be between ")
csCZ("")
deDE("")
frFR("")
huHU("Az időpont a köv. kettő között legyen: ")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Time must be between ")
zhCN("")

T_("Please enter no more than %d characters.")
csCZ("Text nesmí být delší než %d znaků.")
deDE("Bitte geben Sie nicht mehr als %d Zeichen ein.")
frFR("Veuillez ne pas saisir plus de %d caractères.")
huHU("Ne adjon be többet %d karakternél.")
itIT("Non scrivere più di %d caratteri.")
plPL("Proszę wprowadzić nie więcej niż %d znaków.")
ruRU("Пожайлуста, введите не более чем %d символов.")
srSP("Molim vas unesite najviše %d slova.")
trTR("Lütfen en fazla %d karakter girin.")
zhCN("输入请不要超过%d字符")


// t.cpp

T_("date-format\a%2:02d/%3:02d/%1:4d")
csCZ("%3:02d.%2:02d.%1:04d")
deDE("%3:02d.%2:02d.%1:4d")
frFR("%3:02d/%2:02d/%1:04d")
huHU("%1:04d.%2:02d.%3:02d.")
itIT("%3:02d/%2:02d/%1:04d")
plPL("%3:02d.%2:02d.%1:04d")
ruRU("%3:02d.%2:02d.%1:04d")
srSP("%3:02d.%2:02d.%1:04d")
trTR("%3:02d.%2:02d.%1:04d")
zhCN("%2:02d/%3:02d/%1:4d")

T_("date-scan\amdy")
csCZ("dmy")
deDE("dmy")
frFR("dmy")
huHU("ymd")
itIT("dmy")
plPL("dmy")
ruRU("dmy")
srSP("dmy")
trTR("dmy")
zhCN("mdy")

T_("date-filter\aA/\a .-")
csCZ(".\a /,")
deDE("A/\a .-")
frFR("/\a .,")
huHU("A.\a .-")
itIT("/\a .,")
plPL("\a .,-/")
ruRU(".\a /,")
srSP(".\a /,")
trTR(".\a /,")
zhCN("A/\a .-")


// Lang.cpp

T_("Invalid language specification.")
csCZ("Chybná specifikace jazyka.")
deDE("Ungültige Sprachenbezeichnung")
frFR("Langue spécifiée invalide.")
huHU("Érvénytelen nyelvbeállítás")
itIT("Lingua specificata non valida.")
plPL("Niepoprawna specyfikacja języka.")
ruRU("Неправильная спецификация языка.")
srSP("Nevalidna specifikacija jezika.")
trTR("Geçersiz dil.")
zhCN("无效语言指示")


// Obsolete

T_("invalid day number.")
csCZ("neplatné číslo dne.")
deDE("Ungültige Tageszahl")
frFR("jour invalide.")
huHU("érvénytelen nap.")
itIT("giorno non valido.")
plPL("niepoprawny numer dnia.")
ruRU("неправильное число дня месяца.")
srSP("nevalidan dan.")
trTR("geçersiz gün.")
zhCN("无效天数")

T_("invalid month number.")
csCZ("neplatné číslo měsíce.")
deDE("Ungültige Monatszahl")
frFR("mois invalide.")
huHU("érvénytelen hónap.")
itIT("mese non valido.")
plPL("niepoprawny numer miesiąca.")
ruRU("неправильное число месяца.")
srSP("nevalidan mesec.")
trTR("geçersiz ay.")
zhCN("无效月数")

T_("invalid year number.")
csCZ("neplatné číslo roku.")
deDE("Ungültige Jahreszahl")
frFR("année invalide.")
huHU("érvénytelen év.")
itIT("anno non valido.")
plPL("niepoprawny numer roku.")
ruRU("неправильное число года.")
srSP("nevalidana godina.")
trTR("geçersiz yıl.")
zhCN("无效年数")

T_("invalid hour number.")
csCZ("chybné číslo hodiny.")
deDE("Ungültige Stundenzahl")
frFR("heure invalide.")
huHU("érvénytelen óra.")
itIT("ora non valida.")
plPL("niepoprawna wartość godziny.")
ruRU("неправильное число часа.")
srSP("nevalidan sat.")
trTR("geçersiz saat.")
zhCN("无效小时")

T_("invalid minute number.")
csCZ("chybné číslo minuty.")
deDE("Ungültige Minutenzahl")
frFR("minute invalide.")
huHU("érvénytelen perc.")
itIT("minuti non valido.")
plPL("niepoprawna wartość minuty.")
ruRU("неправильное число минуты.")
srSP("nevalidna minuta.")
trTR("geçersiz dakika.")
zhCN("无效分")

T_("invalid second number.")
csCZ("chybné číslo sekundy.")
deDE("Ungültige Sekundenzahl")
frFR("seconde invalide.")
huHU("érvénytelen másodperc.")
itIT("secondi non valido.")
plPL("niepoprawna druga wartość.")
ruRU("неправильное число секунды.")
srSP("nevalidna sekunda.")
trTR("geçersiz saniye.")
zhCN("无效秒")

T_("invalid character '%c' following date/time.")
csCZ("neplatný znak '%c' za koncem data.")
deDE("Ungültiges Zeichen '%c' folgt Datum/Zeit.")
frFR("caractère invalide '%c' suivant la date.")
huHU("érvénytelen karakter '%c' a dátum/idő mellett.")
itIT("carattere non valido '%c' dopo la data.")
plPL("niepoprawny znak '%c' na końcu daty/czasu.")
ruRU("неправильный символ '%c' идущий за датой/временем.")
srSP("nevalidni karakter '%c' posle datuma/vremena.")
trTR("girilen tarih/zaman bilgisi içindeki '%c' geçersiz bir karakterdir.")
zhCN("日期/时间后跟字符 '%c' 无效")

T_("invalid day number %d - February in year %d has only %d days.")
csCZ("neplatné číslo dne %d - únor v roce %d má pouze %d dní.")
deDE("Ungültige Tagesnummer %d - Februar im Jahr %d hat nur %d Tage.")
frFR("jour %d invalide pour Février qui n'a que %d jours.")
huHU("érvénytelen nap %d - a február a(z) %d évben csak %d napos.")
itIT("Febbraio ha solo %d giorni.")
plPL("niepoprawny numer dnia %d - Luty w roku %d ma tylko %d dni.")
ruRU("неправильное число месяца %d - В феврале "
     "%d года только %d дней.")
srSP("nevalidan dan %d - Februar u godini %d ima %d dana.")
trTR("%d geçersiz bir gün sayısıdır - %d yılında Şubat ayı %d gün "
     "çeker.")
zhCN("无效天数 %d -  %d年二月只有%d天.")

T_("invalid day number %d - %month has only %d days.")
csCZ("neplatné číslo dne %d - %month má pouze %d dní.")
deDE("Ungültige Tagesnummer %d - %month hat nur %d Tage.")
frFR("jour %d invalide pour %month qui n'a que %d jours.")
huHU("érvénytelen nap %d - %month csak % napos.")
itIT("Giorno non valido %d - %month ha solo %d giorni.")
plPL("niepoprawny numer dnia - %month ma tylko %d dni.")
ruRU("неправильное число месяца %d - В %month только "
     "%d дней.")
srSP("nevalidan dan %d - %month ima %d dana.")
trTR("%d geçersiz bir gün sayısıdır - %month ayı %d gün çeker.")
zhCN("无效天数 %d - %month月只有 %d 天.")

T_("exceeded valid range (lower bound: %`).")
csCZ("překročení povoleného rozsahu (dolní mez: %`).")
deDE("Gültigkeitsbereich unterschritten (untere Grenze: %`).")
frFR("validité de l'intervalle dépassée (limite inférieure : %d`).")
huHU("érvényes tartomány alatt (alsó határ: %`).")
itIT("range valido superato (limite inferiore: %`).")
plPL("przekroczono dopuszczalny zakres (dolna granica: %`).")
ruRU("превышен допустимый предел (нижний предел: "
     "%`).")
srSP("prekoračena validna granica (donja granica: %`).")
trTR("Geçerli aralık aşıldı (alt sınır: %`).")
zhCN("超出有效范围(下限:%`).")

T_("exceeded valid range (upper bound: %`).")
csCZ("překročení povoleného rozsahu (horní mez: %`).")
deDE("Gültigkeitsbereich überschritten (obere Grenze: %`).")
frFR("validité de l'intervalle dépassée (limite supérieure : %d`).")
huHU("érvényes tartomány fölött (felső határ: %`)")
itIT("range valido superato (limite superiore: %`).")
plPL("przekroczono dopuszczalny zakres (górna granica: %`).")
ruRU("превышен допустимый предел (верхний предел: "
     "%`).")
srSP("prekoračena validna granica (gornja granica: %`).")
trTR("Geçerli aralık aşıldı (üst sınır: %`).")
zhCN("超出有效范围(上限:%`).")

T_("Invalid date/time: digit expected, found character")
csCZ("Chybné datum/čas: očekávána číslice, nalezen znak")
deDE("Ungültige(s) Datum/Zeit: Ziffer erwartet, Zeichen vorgefunden")
frFR("Date/heure invalide : chiffre attendu, caractère détecté")
huHU("érvénytelen dátum/idő: számjegy helyett más karakter áll")
itIT("Data/ora non valida")
plPL("Niepoprawna data/czas: oczekiwano cyfry, znaleziono znak")
ruRU("Неправильные дата/время: ожидается цифра, "
     "а найден символ")
srSP("Nevalidan datum/vreme: očekuje se cifra, pronađen karakter")
trTR("Geçersiz tarih/zaman: sayı olması gereken yerde harf var")
zhCN("无效日期/时间:只能是数字,不能为字符")

T_("Invalid date/time:")
csCZ("Chybné datum/čas:")
deDE("Ungültige(s) Datum/Zeit:")
frFR("Date/heure invalide :")
huHU("érvénytelen dátum/idő")
itIT("Data/ora non valida:")
plPL("Niepoprawna data/czas:")
ruRU("Неправильные дата/время:")
srSP("Nevalidan datum/vreme:")
trTR("Geçersiz tarih/zaman:")
zhCN("无效日期/时间:")
