
// Util.cpp

T_("Aborted by user.")
csCZ("Operace byla přerušena uživatelem.")
frFR("Annulé par l'utilisateur.")
huHU("Megszakította a felhasználó")
itIT("Annullato dall'utente")
ruRU("Прервано пользователем")
srSP("Prekinuto od strane korisnika.")


// TimeDate.cpp

T_("date\vSaturday")
csCZ("Sobota")
frFR("Samedi")
huHU("Szombat")
itIT("Sabato")
ruRU("Воскресенье")
srSP("Subota")

T_("date\vMonday")
csCZ("Pondělí")
frFR("Lundi")
huHU("Hétfő")
itIT("Lunedì")
ruRU("Понедельник")
srSP("Ponedeljak")

T_("date\vTuesday")
csCZ("Úterý")
frFR("Mardi")
huHU("Kedd")
itIT("Martedì")
ruRU("Вторник")
srSP("Utorak")

T_("date\vWednesday")
csCZ("Středa")
frFR("Mercredi")
huHU("Szerda")
itIT("Mercoledì")
ruRU("Среда")
srSP("Sreda")

T_("date\vThursday")
csCZ("Čtvrtek")
frFR("Jeudi")
huHU("Csütörtök")
itIT("Giovedì")
ruRU("Четверг")
srSP("Četvrtak")

T_("date\vFriday")
csCZ("Pátek")
frFR("Vendredi")
huHU("Péntek")
itIT("Venerdì")
ruRU("Пятница")
srSP("Petak")

T_("date\vSunday")
csCZ("Neděle")
frFR("Dimanche")
huHU("Vasárnap")
itIT("Domenica")
ruRU("Суббота")
srSP("Nedelja")

T_("date\vSa")
csCZ("Ne")
frFR("Sam")
huHU("Szo")
itIT("Sa")
ruRU("Вс")
srSP("Ne")

T_("date\vMo")
csCZ("Po")
frFR("Lun")
huHU("Hé")
itIT("Lu")
ruRU("Пн")
srSP("Po")

T_("date\vTu")
csCZ("Út")
frFR("Mar")
huHU("Ke")
itIT("Ma")
ruRU("Вт")
srSP("Ut")

T_("date\vWe")
csCZ("St")
frFR("Mer")
huHU("Sze")
itIT("Me")
ruRU("Ср")
srSP("Sr")

T_("date\vTh")
csCZ("Čt")
frFR("Jeu")
huHU("Csüt")
itIT("Gi")
ruRU("Чт")
srSP("Če")

T_("date\vFr")
csCZ("Pa")
frFR("Ven")
huHU("Pé")
itIT("Ve")
ruRU("Пт")
srSP("Pe")

T_("date\vSu")
csCZ("So")
frFR("Dim")
huHU("Vas")
itIT("Do")
ruRU("Сб")
srSP("Su")

T_("date\vJanuary")
csCZ("Leden")
frFR("Janvier")
huHU("Január")
itIT("Gennaio")
ruRU("Январь")
srSP("Januar")

T_("date\vFebruary")
csCZ("Únor")
frFR("Février")
huHU("Február")
itIT("Febbraio")
ruRU("Февраль")
srSP("Februar")

T_("date\vMarch")
csCZ("Březen")
frFR("Mars")
huHU("Március")
itIT("Marzo")
ruRU("Март")
srSP("Mart")

T_("date\vApril")
csCZ("Duben")
frFR("Avril")
huHU("Április")
itIT("Aprile")
ruRU("Апрель")
srSP("April")

T_("date\vMay")
csCZ("Květen")
frFR("Mai")
huHU("Május")
itIT("Maggio")
ruRU("Май")
srSP("Maj")

T_("date\vJune")
csCZ("Červen")
frFR("Juin")
huHU("Június")
itIT("Giugno")
ruRU("Июнь")
srSP("Jun")

T_("date\vJuly")
csCZ("Červenec")
frFR("Juillet")
huHU("Július")
itIT("Luglio")
ruRU("Июль")
srSP("Jul")

T_("date\vAugust")
csCZ("Srpen")
frFR("Août")
huHU("Augusztus")
itIT("Agosto")
ruRU("Август")
srSP("Avgust")

T_("date\vSeptember")
csCZ("Září")
frFR("Septembre")
huHU("Szeptember")
itIT("Settembre")
ruRU("Сентябрь")
srSP("Septembar")

T_("date\vOctober")
csCZ("Říjen")
frFR("Octobre")
huHU("Október")
itIT("Ottobre")
ruRU("Октябрь")
srSP("Oktobar")

T_("date\vNovember")
csCZ("Listopad")
frFR("Novembre")
huHU("November")
itIT("Novembre")
ruRU("Ноябрь")
srSP("Novembar")

T_("date\vDecember")
csCZ("Prosinec")
frFR("Décembre")
huHU("December")
itIT("Dicembre")
ruRU("Декабрь")
srSP("Decembar")

T_("sdate\vJan")
csCZ("Led")
frFR("Jan")
huHU("Jan")
itIT("Gen")
ruRU("Янв")
srSP("Jan")

T_("sdate\vFeb")
csCZ("Úno")
frFR("Fév")
huHU("Feb")
itIT("Feb")
ruRU("Фев")
srSP("Feb")

T_("sdate\vMar")
csCZ("Bře")
frFR("Mar")
huHU("Márc")
itIT("Mar")
ruRU("Мрт")
srSP("Mar")

T_("sdate\vApr")
csCZ("Dub")
frFR("Avr")
huHU("Ápr")
itIT("Apr")
ruRU("Апр")
srSP("Apr")

T_("sdate\vMay")
csCZ("Kvě")
frFR("Mai")
huHU("Máj")
itIT("Mag")
ruRU("Май")
srSP("Maj")

T_("sdate\vJun")
csCZ("Čer")
frFR("Jun")
huHU("Jún")
itIT("Giu")
ruRU("Инь")
srSP("Jun")

T_("sdate\vJul")
csCZ("Čec")
frFR("Jui")
huHU("Júl")
itIT("Lug")
ruRU("Иль")
srSP("Jul")

T_("sdate\vAug")
csCZ("Srp")
frFR("Aou")
huHU("Aug")
itIT("Ago")
ruRU("Авг")
srSP("Avg")

T_("sdate\vSep")
csCZ("Zář")
frFR("Sep")
huHU("Szept")
itIT("Set")
ruRU("Сен")
srSP("Sep")

T_("sdate\vOct")
csCZ("Říj")
frFR("Oct")
huHU("Okt")
itIT("Ott")
ruRU("Окт")
srSP("Okt")

T_("sdate\vNov")
csCZ("Lis")
frFR("Nov")
huHU("Nov")
itIT("Nov")
ruRU("Ноя")
srSP("Nov")

T_("sdate\vDec")
csCZ("Pro")
frFR("Déc")
huHU("Dec")
itIT("Dic")
ruRU("Дек")
srSP("Dec")


// Convert.cpp

T_("Invalid number !")
csCZ("Chybný zápis čísla !")
frFR("Nombre invalide !")
huHU("Érvénytelen szám")
itIT("Numero non valido !")
ruRU("Неправильное число!")
srSP("Pogrešan broj!")

T_("Invalid date !")
csCZ("Chybný zápis data !")
frFR("Date invalide !")
huHU("Érvénytelen dátum")
itIT("Data non valida !")
ruRU("Неправильная дата!")
srSP("Pogrešan datum!")

T_("Null value not allowed.")
csCZ("Hodnota nesmí být prázdná.")
frFR("Valeur nulle non autorisée.")
huHU("Nullérték nem megengedett")
itIT("Lo zero non è ammesso")
ruRU("Нулевое значение не разрешено.")
srSP("Bez vrednosti nisu dopuštene.")

T_("Number must be between %d and %d.")
csCZ("Číslo musí být v rozsahu %d až %d.")
frFR("Le nombre doit être compris entre %d et %d.")
huHU("A számnak %d és %d közé kell esnie")
itIT("Il numero deve essere compreso tra %d e %d.")
ruRU("Число должно быть в пределах между %d и "
     "%d")
srSP("Broj mora biti između %d i %d.")

T_("Number must be between %g and %g.")
csCZ("Číslo musí být v rozsahu %g až %g.")
frFR("Le nombre doit être compris entre %g et %g.")
huHU("A számnak %g és %g közé kell esnie")
itIT("Il numero deve essere compreso tra %g e %g.")
ruRU("Число должно быть в пределах между %g и "
     "%g")
srSP("Broj mora biti između %g i %g.")

T_("Date must be between ")
csCZ("Datum musí být v rozsahu ")
frFR("La date doit comprise entre")
huHU("A dátum érvényes határai ")
itIT("La data deve essere compre tra ")
ruRU("Дата должна быть в пределах ")
srSP("Datum mora biti između ")

T_("range\v and ")
csCZ(" až ")
frFR(" et ")
huHU(" és ")
itIT(" e ")
ruRU(" и ")
srSP(" i ")

T_("invalid day number.")
csCZ("neplatné číslo dne.")
frFR("jour invalide.")
huHU("érvénytelen nap.")
itIT("giorno non valido.")
ruRU("неправильное число дня месяца.")
srSP("nevalidan dan.")

T_("invalid month number.")
csCZ("neplatné číslo měsíce.")
frFR("mois invalide.")
huHU("érvénytelen hónap.")
itIT("mese non valido.")
ruRU("неправильное число месяца.")
srSP("nevalidan mesec.")

T_("invalid year number.")
csCZ("neplatné číslo roku.")
frFR("année invalide.")
huHU("érvénytelen év.")
itIT("anno non valido.")
ruRU("неправильное число года.")
srSP("nevalidana godina.")

T_("invalid hour number.")
csCZ("chybné číslo hodiny.")
frFR("heure invalide.")
huHU("érvénytelen óra.")
itIT("ora non valida.")
ruRU("неправильное число часа.")
srSP("nevalidan sat.")

T_("invalid minute number.")
csCZ("chybné číslo minuty.")
frFR("minute invalide.")
huHU("érvénytelen perc.")
itIT("minuti non valido.")
ruRU("неправильное число минуты.")
srSP("nevalidna minuta.")

T_("invalid second number.")
csCZ("chybné číslo sekundy.")
frFR("seconde invalide.")
huHU("érvénytelen másodperc.")
itIT("secondi non valido.")
ruRU("неправильное число секунды.")
srSP("nevalidna sekunda.")

T_("invalid character '%c' following date/time.")
csCZ("neplatný znak '%c' za koncem data.")
frFR("caractère invalide '%c' suivant la date.")
huHU("érvénytelen karakter '%c' a dátum/idő mellett.")
itIT("carattere non valido '%c' dopo la data.")
ruRU("неправильный символ '%c' идущий за датой/временем.")
srSP("nevalidni karakter '%c' posle datuma/vremena.")

T_("invalid day number %d - February in year %d has only %d days.")
csCZ("neplatné číslo dne %d - únor v roce %d má pouze %d dní.")
frFR("jour %d invalide pour Février qui n'a que %d jours.")
huHU("érvénytelen nap %d - a február a(z) %d évben csak %d napos.")
itIT("Febbraio ha solo %d giorni.")
ruRU("неправильное число месяца %d - В феврале "
     "%d года только %d дней.")
srSP("nevalidan dan %d - Februar u godini %d ima %d dana.")

T_("invalid day number %d - %month has only %d days.")
csCZ("neplatné číslo dne %d - %month má pouze %d dní.")
frFR("jour %d invalide pour %month qui n'a que %d jours.")
huHU("érvénytelen nap %d - %month csak % napos.")
itIT("Giorno non valido %d - %month ha solo %d giorni.")
ruRU("неправильное число месяца %d - В %month только "
     "%d дней.")
srSP("nevalidan dan %d - %month ima %d dana.")

T_("exceeded valid range (lower bound: %`).")
csCZ("překročení povoleného rozsahu (dolní mez: %`).")
frFR("validité de l'intervalle dépassée (limite inférieure : %d`).")
huHU("érvényes tartomány alatt (alsó határ: %`).")
itIT("range valido superato (limite inferiore: %`).")
ruRU("превышен допустимый предел (нижний предел: "
     "%`).")
srSP("prekoračena validna granica (donja granica: %`).")

T_("exceeded valid range (upper bound: %`).")
csCZ("překročení povoleného rozsahu (horní mez: %`).")
frFR("validité de l'intervalle dépassée (limite supérieure : %d`).")
huHU("érvényes tartomány fölött (felső határ: %`)")
itIT("range valido superato (limite superiore: %`).")
ruRU("превышен допустимый предел (верхний предел: "
     "%`).")
srSP("prekoračena validna granica (gornja granica: %`).")

T_("Invalid date/time: digit expected, found character")
csCZ("Chybné datum/čas: očekávána číslice, nalezen znak")
frFR("Date/heure invalide : chiffre attendu, caractère détecté")
huHU("érvénytelen dátum/idő: számjegy helyett más karakter áll")
itIT("Data/ora non valida")
ruRU("Неправильные дата/время: ожидается цифра, "
     "а найден символ")
srSP("Nevalidan datum/vreme: očekuje se cifra, pronađen karakter")

T_("Invalid date/time:")
csCZ("Chybné datum/čas:")
frFR("Date/heure invalide :")
huHU("érvénytelen dátum/idő")
itIT("Data/ora non valida:")
ruRU("Неправильные дата/время:")
srSP("Nevalidan datum/vreme:")

T_("Please enter no more than %d characters.")
csCZ("Text nesmí být delší než %d znaků.")
frFR("Veuillez ne pas saisir plus de %d caractères.")
huHU("Ne adjon be többet %d karakternél.")
itIT("Non scrivere più di %d caratteri.")
ruRU("Пожайлуста, введите не более чем %d символов.")
srSP("Molim vas unesite najviše %d slova.")


// t.cpp

T_("date-format\a%2:02d/%3:02d/%1:4d")
csCZ("%3:02d.%2:02d.%1:04d")
frFR("%3:02d/%2:02d/%1:04d")
huHU("%1:02d/%2:02d/%3:4d")
itIT("%3:02d/%2:02d/%1:04d")
ruRU("%3:02d.%2:02d.%1:04d")
srSP("%3:02d.%2:02d.%1:04d")

T_("date-scan\amdy")
csCZ("dmy")
frFR("dmy")
huHU("ymd")
itIT("dmy")
ruRU("dmy")
srSP("dmy")

T_("date-filter\aA/\a .-")
csCZ(".\a /,")
frFR("/\a .,")
huHU("A.\a .-")
itIT("/\a .,")
ruRU(".\a /,")
srSP(".\a /,")


// Lang.cpp

T_("Invalid language specification.")
csCZ("Chybná specifikace jazyka.")
frFR("Langue spécifiée invalide.")
huHU("Érvénytelen nyelvbeállítás")
itIT("Lingua specificata non valida.")
ruRU("Неправильная спецификация языка.")
srSP("Nevalidna specifikacija jezika.")
