
// Editor.cpp

T_("Units")
csCZ("Jednotky")
deDE("Einheiten")
frFR("Unités")
huHU("Egységek")
itIT("Unit�")
plPL("Jednostki")
ruRU("Единицы")
srSP("Jedinice")

T_("%d%% of width")
csCZ("%d%% šířky")
deDE("%d%% der Breite")
frFR("%d%% de la largeur")
huHU("%d%% szélesség")
itIT("%d%% di larghezza")
plPL("%d%% szerokości")
ruRU("%d%% длинны")
srSP("%d%% širine")

T_("None")
csCZ("Není")
deDE("Ohne")
frFR("Aucun")
huHU("Semmi")
itIT("Nulla")
plPL("Brak")
ruRU("Нет")
srSP("NIšta")

T_("Hyperlink")
csCZ("Propojení")
deDE("Hyperlink")
frFR("Hyperlien")
huHU("Hiperhivatkozás")
itIT("Collegamento")
plPL("Odnośnik")
ruRU("Ссылка")
srSP("Hiperveza")

T_("Paragraph label")
csCZ("Návěští odstavce")
deDE("Absatzmarke")
frFR("Marque de paragraphe")
huHU("Bekezdéscímke")
itIT("Etichetta paragrafo")
plPL("Etykieta paragrafu")
ruRU("Метка параграфа")
srSP("Labela paragrafa")

T_("Label")
csCZ("Návěští")
deDE("Absatz")
frFR("Marque")
huHU("Címke")
itIT("Etichetta")
plPL("Etykieta")
ruRU("Метка")
srSP("Labela")

T_("Font face")
csCZ("Písmo")
deDE("Schriftart")
frFR("Police")
huHU("Font jelleg")
itIT("Tipo carattere")
plPL("Czcionka")
ruRU("Шрифт")
srSP("Izgled fonta")

T_("Language")
csCZ("Jazyk")
deDE("Sprache")
frFR("Langue")
huHU("Nyelv")
itIT("Lingua")
plPL("Język")
ruRU("Язык")
srSP("Jezik")

T_("Font height")
csCZ("Výška písma")
deDE("Schriftgrad")
frFR("Taille de police")
huHU("Font magasság")
itIT("Altezza carattere")
plPL("Wysokość czcionki")
ruRU("Высота шрифта")
srSP("Visina fonta")

T_("Index entry")
csCZ("Resjtříkový odkaz")
deDE("Indexeintrag")
frFR("Marque l'index")
huHU("Belépés mutató")
itIT("")
plPL("Indeks")
ruRU("Точка входа")
srSP("Indeks ulaza")

T_("Go to label")
csCZ("Přejít na návěští")
deDE("Gehe zu Marke")
frFR("Aller à la marque")
huHU("Ugrás a címkéhez")
itIT("Vai ad etichetta")
plPL("Idź do etykiety")
ruRU("Перейти к метке")
srSP("Idi na labelu")

T_("Go to index entry")
csCZ("Přejít na rejstříkový odkaz")
deDE("Gehe zu Indexeintrag")
frFR("Aller à la marque d'index")
huHU("Ugrás a belépés mutatóhoz")
itIT("")
plPL("Przejdź do indeksu")
ruRU("Перейти к точке входа")
srSP("Idi na indeks ulaza")

T_("Text color")
csCZ("Barva textu")
deDE("Textfarbe")
frFR("Couleur du texte")
huHU("Szövegszín")
itIT("Colore testo")
plPL("Kolor tekstu")
ruRU("Цвет текста")
srSP("Boja teksta")

T_("Background color")
csCZ("Barva pozadí")
deDE("Hintergrundfarbe")
frFR("Couleur d'arrière plan")
huHU("Háttérszín")
itIT("Colore sfondo")
plPL("Kolor tła")
ruRU("Цвет фона")
srSP("Pozadinska boja")

T_("Store as style")
csCZ("Uložit jako styl")
deDE("Als Stil speichern")
frFR("Enregistrer comme style")
huHU("Tárolás stílusként")
itIT("Salva come stile")
plPL("Zapisz jako styl")
ruRU("Сохранить как стиль")
srSP("Sačuvaj kao stil")

T_("Style manager")
csCZ("Styly")
deDE("Stilmanager")
frFR("Gestionnaire de styles")
huHU("Stíluskezelő")
itIT("Manager stili")
plPL("Menadżer styli")
ruRU("Менеджер стилей")
srSP("Menadžer stilova")

T_("Style")
csCZ("Styl")
deDE("Stil")
frFR("Style")
huHU("Stílus")
itIT("Stile")
plPL("Styl")
ruRU("Стиль")
srSP("Stil")

T_("Find / Replace")
csCZ("Vyhledat / Nahradit")
deDE("Suchen / Ersetzen")
frFR("Rechercher / Remplacer")
huHU("Keresés / Csere")
itIT("Trova / Sostituisci")
plPL("Znajdź / Zamień")
ruRU("Найти / Заменить")
srSP("Pronađi / Zameni")


// Mouse.cpp

T_("Object position..")
csCZ("Pozice objektu..")
deDE("Objektposition ...")
frFR("Position de l'objet")
huHU("Objektum pozíció..")
itIT("Posizione oggetto..")
plPL("Pozycja obiektu..")
ruRU("Позиция объекта...")
srSP("Pozicija objekta..")

T_("3 pt up")
csCZ("3 body nahoru")
deDE("3 pt hoch")
frFR("3 points vers le haut")
huHU("3 pont fel")
itIT("3 pt su")
plPL("3 pt w górę")
ruRU("на 3 pt больше")
srSP("3 pt na gore")

T_("2 pt up")
csCZ("2 body nahoru")
deDE("2 pt hoch")
frFR("2 points vers le haut")
huHU("2 pont fel")
itIT("2 pt su")
plPL("2 pt w dół")
ruRU("на 2 pt больше")
srSP("2 pt na gore")

T_("1 pt up")
csCZ("1 bod nahoru")
deDE("1 pt hoch")
frFR("1 point vers le haut")
huHU("1 pont fel")
itIT("1 pt su")
plPL("1 pt w górę")
ruRU("на 1 pt больше")
srSP("1 pt na gore")

T_("Baseline")
csCZ("Základní pozice")
deDE("Schriftlinie")
frFR("Ligne de base")
huHU("Alapvonal")
itIT("Normale")
plPL("Linia bazowa")
ruRU("Базовая линия")
srSP("Osnovna linija")

T_("1 pt down")
csCZ("1 bod dolů")
deDE("1 pt runter")
frFR("1 point vers le bas")
huHU("1 pont le")
itIT("1 pt gi�")
plPL("1 pt w dół")
ruRU("на 1 pt меньше")
srSP("1 pt na dole")

T_("2 pt down")
csCZ("2 body dolů")
deDE("2 pt runter")
frFR("2 points vers le bas")
huHU("2 pont le")
itIT("2 pt gi�")
plPL("2 pt w dół")
ruRU("на 2 pt меньше")
srSP("2 pt na dole")

T_("3 pt down")
csCZ("3 body dolů")
deDE("3 pt runter")
frFR("3 points vers le bas")
huHU("3 pont le")
itIT("3 pt gi�")
plPL("3 pt w dół")
ruRU("на 3 pt меньше")
srSP("3 pt na dole")

T_("Add to user dictionary")
csCZ("Přidat do uživatelského slovníku")
deDE("Zum Benutzerwörterbuch hinzufügen")
frFR("Ajouter au dictionnaire utilisateur")
huHU("Hozzáadás a felhasználó mappájához")
itIT("Aggiungi al dizionario")
plPL("Dodaj do słownika użytkownika")
ruRU("Добавить в словарь пользователя")
srSP("Dodaj u korisnički rečnik")


// Formating.cpp

T_("Index Entry")
csCZ("Rejstříkový Odkaz")
deDE("Indexeintrag")
frFR("Marque d'index")
huHU("Belépés mutató")
itIT("")
plPL("Index")
ruRU("Точка входа")
srSP("Indeks ulaza")

T_("Left")
csCZ("Vlevo")
deDE("Links")
frFR("Gauche")
huHU("Bal")
itIT("Sinistra")
plPL("Do lewej")
ruRU("Влево")
srSP("Levo")

T_("Right")
csCZ("Vpravo")
deDE("Rechts")
frFR("Droite")
huHU("Jobb")
itIT("Destra")
plPL("Do prawej")
ruRU("Вправо")
srSP("Desno")

T_("Center")
csCZ("Na střed")
deDE("Mitte")
frFR("Centrer")
huHU("Közép")
itIT("Centro")
plPL("Wyśrodkowany")
ruRU("По центру")
srSP("Na sredini")

T_("No fill")
csCZ("Bez výplně")
deDE("Kein Füllzeichen")
frFR("Ne pas remplir")
huHU("Nincs kitöltés")
itIT("Nessuno riempimento")
plPL("Bez wypełnienia")
ruRU("Без заливки")
srSP("Bez ispune")

T_("Fill with ....")
csCZ("Vyplnit ....")
deDE("Füllen mit ....")
frFR("Remplir avec ....")
huHU("Kitöltés ....")
itIT("Riempi con ....")
plPL("Wypełnij ....")
ruRU("Залить ....")
srSP("Ispuni sa ....")

T_("Fill with ----")
csCZ("Vyplnit ----")
deDE("Füllen mit ----")
frFR("Remplir avec ----")
huHU("Kitöltés ----")
itIT("Riempi con ----")
plPL("Wypełnij ----")
ruRU("Залить ----")
srSP("Ispuni sa ----")

T_("Fill with __")
csCZ("Vyplnit __")
deDE("Füllen mit ____")
frFR("Remplir avec __")
huHU("Kitöltés __")
itIT("Riempi con __")
plPL("Wypełnij __")
ruRU("Залить __")
srSP("Ispuni sa __")

T_("Remove")
csCZ("Odstranit")
deDE("Entfernen")
frFR("Eliminer")
huHU("Eltávolítás")
itIT("Elimina")
plPL("Usuń")
ruRU("Удалить")
srSP("Uklonu")

T_("Object position")
csCZ("Pozice objektu")
deDE("Objektposition")
frFR("Position de l'objet")
huHU("Objektum pozíció")
itIT("Posizione oggetto")
plPL("Pozycja obiektu")
ruRU("Позиция объекта")
srSP("Pozicija objekta")


// ParaFormat.cpp

T_("Centered")
csCZ("Uprostřed")
deDE("Zentriert")
frFR("Centré")
huHU("Középre zárt")
itIT("Centrato")
plPL("Wyśrodkowany")
ruRU("Центрованный")
srSP("Centrirano")

T_("....")
csCZ("....")
deDE("....")
frFR("....")
huHU("....")
itIT("....")
plPL("....")
ruRU("")
srSP("....")

T_("----")
csCZ("----")
deDE("----")
frFR("----")
huHU("----")
itIT("----")
plPL("----")
ruRU("")
srSP("----")

T_("__")
csCZ("__")
deDE("____")
frFR("__")
huHU("__")
itIT("__")
plPL("__")
ruRU("")
srSP("__")

T_("Tab position")
csCZ("Pozice tabelace")
deDE("Tabulatorposition")
frFR("Position de tabulation")
huHU("Tabulátor pozíció")
itIT("Posizione tabulatore")
plPL("Pozycja")
ruRU("Позиция табуляции")
srSP("Pozicija tabulatora")

T_("Type")
csCZ("Typ")
deDE("Typ")
frFR("Type")
huHU("Típus")
itIT("Tipo")
plPL("Wyrównanie")
ruRU("Тип")
srSP("Tip")

T_("Fill")
csCZ("Výplň")
deDE("Füllen")
frFR("Remplir")
huHU("Kitöltés")
itIT("Riempi")
plPL("Wypełnienie")
ruRU("Заливка")
srSP("Ispuni")

T_("Paragraph format")
csCZ("Formát odstavce")
deDE("Absatzformat")
frFR("Format de paragraphe")
huHU("Bekezdésformátum")
itIT("Formato paragrafo")
plPL("Format paragrafu")
ruRU("Формат параграфа")
srSP("Fromat paragrafa")

T_("Set style")
csCZ("Nastavit styl")
deDE("Stil einstellen")
frFR("Utiliser le style")
huHU("Stílus beállítása")
itIT("Imposta stile")
plPL("Ustaw styl")
ruRU("Установить стиль")
srSP("Postavi stil")

T_("New style no. %d")
csCZ("Nový styl č. %d")
deDE("Neuer Stil Nr. %d")
frFR("Nouveau style n° %d")
huHU("Új stílus szám %d")
itIT("Nuovo stile no. %d")
plPL("Nowy styl numer %d")
ruRU("Новый стиль номер %d")
srSP("Novi stil br. %d")

T_("Create new style..")
csCZ("Vytvořit nový styl..")
deDE("Neuen Stil erstellen ...")
frFR("Créer un nouveau style..")
huHU("Új stílus létrehozása")
itIT("Crea nuovo stile..")
plPL("Utwórz nowy styl..")
ruRU("Создать новый стиль..")
srSP("Napravi novi stil..")

T_("Remove style")
csCZ("Odstranit styl")
deDE("Stil entfernen")
frFR("Supprimer le style")
huHU("Stílus eltávolítása")
itIT("Rimuovi stile")
plPL("Usuń styl")
ruRU("Удалить стиль")
srSP("Ukloni stil")

T_("Rename..")
csCZ("Přejmenovat..")
deDE("Umbenennen ...")
frFR("Renommer..")
huHU("Átnevezés")
itIT("Rinomina..")
plPL("Zmień nazwę..")
ruRU("Переименовать..")
srSP("Preimenuj..")

T_("Styles")
csCZ("Styly")
deDE("Stile")
frFR("Styles")
huHU("Stílusok")
itIT("Stili")
plPL("Style")
ruRU("Стили")
srSP("Stilovi")


// Table.cpp

T_("Insert table")
csCZ("Vložit tabulku")
deDE("Tabelle einfügen")
frFR("Insérer un tableau")
huHU("Táblázat beszúrása")
itIT("Inserisci tbella")
plPL("Wstaw tabelę")
ruRU("Вставить таблицу")
srSP("Ubaci tabelu")

T_("Table properties")
csCZ("Vlastnosti tabulky")
deDE("Tabelleneigenschaften")
frFR("Propriétés du tableau")
huHU("Táblázat tulajdonságok")
itIT("Propriet� tabella")
plPL("Właściwości tabeli")
ruRU("Свойства таблицы")
srSP("Svojstva tabele")

T_("Split cell")
csCZ("Rozdělit buňku")
deDE("Zelle teilen")
frFR("Diviser la cellule")
huHU("Mező felosztása")
itIT("Dividi cella")
plPL("Podziel komórkę")
ruRU("Разбить ячейки")
srSP("Podeli ćeliju")

T_("Cell properties")
csCZ("Vlastnosti buňky")
deDE("Zelleigenschaften")
frFR("Propriétés de la cellule")
huHU("Mező tulajdonságok")
itIT("Propriet� cella")
plPL("Właściwości komórki")
ruRU("Свойства ячейки")
srSP("Svojstva ćelije")


// Find.cpp

T_("Replace")
csCZ("Nahradit")
deDE("Ersetzen")
frFR("Remplacer")
huHU("Csere")
itIT("Sostituisci")
plPL("Zamień")
ruRU("Заменить")
srSP("Zameni")

T_("Replace in selection")
csCZ("Nahradit ve výběru")
deDE("In der Auswahl ersetzen")
frFR("Remplacer dans la sélection")
huHU("Csere a kijelölésben")
itIT("Sostituisci nella selezione")
plPL("Zamień w selekcji")
ruRU("Заменить в выделении")
srSP("Zameni u izboru")

T_("Find")
csCZ("Vyhledat")
deDE("Suchen")
frFR("Rechercher")
huHU("Keresés")
itIT("Trova")
plPL("Znajdź")
ruRU("Найти")
srSP("Pronađi")


// Tool.cpp

T_("Bold")
csCZ("Tučně")
deDE("Fett")
frFR("Gras")
huHU("Félkövér")
itIT("Grassetto")
plPL("Pogrubienie")
ruRU("Полужирный")
srSP("Masno")

T_("Italic")
csCZ("Kurzíva")
deDE("Kursiv")
frFR("Italique")
huHU("Dőlt")
itIT("Corsivo")
plPL("Kursywa")
ruRU("Наклонный")
srSP("Kurziv")

T_("Underline")
csCZ("Podtržené")
deDE("Unterstrichen")
frFR("Souligné")
huHU("Aláhúzott")
itIT("Sottolineato")
plPL("Podkreślenie")
ruRU("Подчёркнутый")
srSP("Podcrtano")

T_("Strikeout")
csCZ("Přeškrtnuté")
deDE("Durchgestrichen")
frFR("Barré")
huHU("Áthúzott")
itIT("Sbarrato")
plPL("Przekreślenie")
ruRU("Зачёркнутый")
srSP("Precrtano")

T_("Capitals")
csCZ("Kapitálky")
deDE("Kapitälchen")
frFR("Majuscules")
huHU("Nagybetűk")
itIT("Maiuscoletto")
plPL("Kapitaliki")
ruRU("Прописными")
srSP("Velika slova")

T_("Superscript")
csCZ("Horní index")
deDE("Hochgestellt")
frFR("Exposant")
huHU("Felső index")
itIT("Apice")
plPL("Indeks górny")
ruRU("Надстрочный")
srSP("Gornji indeks")

T_("Subscript")
csCZ("Dolní index")
deDE("Tiefgestellt")
frFR("Indice")
huHU("Alsó index")
itIT("Pedice")
plPL("Indeks dolny")
ruRU("Подстрочный")
srSP("Donji indeks")

T_("Show spelling errors")
csCZ("Ukazovat pravopisné chyby")
deDE("Rechtschreibfehler anzeigen")
frFR("Montrer les erreurs de correction")
huHU("Helyesírásellenőrzés")
itIT("Visualizza errori")
plPL("Pokaż błędy pisowni")
ruRU("Показать ошибки орфографии")
srSP("Prikaži jezičke greške")

T_("Justify")
csCZ("Zarovnat do bloku")
deDE("Blocksatz")
frFR("Justifier")
huHU("Margószabályozás")
itIT("Giustificato")
plPL("Wyjustuj")
ruRU("По ширине")
srSP("Poravnaj")

T_("Round bullet")
csCZ("Kulatá zarážka")
deDE("Rundes Aufzählungszeichen")
frFR("Puce ronde")
huHU("Korong")
itIT("Punto elenco circolare")
plPL("Okrągłe wypunktowanie")
ruRU("Круглые списочные маркеры")
srSP("Okruglo označavanje")

T_("White round bullet")
csCZ("Bíla kruhová odrážka")
deDE("Weißes rundes Aufzählungszeichen")
frFR("Puce ronde blanche")
huHU("Fehér korong")
itIT("Punto elenco circolare bianco")
plPL("Białe, okrągłe wypunktowanie")
ruRU("Белые круглые списочные маркеры")
srSP("Belo okruglo označavanje")

T_("Box bullet")
csCZ("Čtvercová odrážka")
deDE("Quadratisches Aufzählungszeichen")
frFR("Puce boîte")
huHU("Négyzet")
itIT("Punto elenco quadrato")
plPL("Kwadratowe wypunktowanie")
ruRU("Квадратные списочные маркеры")
srSP("Kvadratno označvanje")

T_("White box bullet")
csCZ("Bílá čtvercová odrážka")
deDE("Weißes quadratisches Aufzählungszeichen")
frFR("Puce boîte blanche")
huHU("Fehér négyzet")
itIT("Punto elenco quadrato bianco")
plPL("Białe kwadratowe wypunktowanie")
ruRU("Белые квадратные списочные маркеры")
srSP("Belo kvadratno označvanje")

T_("Text bullet")
csCZ("Textová odrážka")
deDE("Textaufzählungszeichen")
frFR("Puce texte")
huHU("Szöveg korong")
itIT("Punto elenco carattere")
plPL("Tekstowe wypunktowanie")
ruRU("Текстовые списочные маркеры")
srSP("Tekst označavanje")

T_("Paragraph format..")
csCZ("Formát odstavce")
deDE("Absatzformat ...")
frFR("Format de paragraphe..")
huHU("Bekezdés formátum..")
itIT("Formato paragrafo..")
plPL("Format paragrafu..")
ruRU("Формат параграфа")
srSP("Format paragrafa..")

T_("To single paragraph")
csCZ("Do jednoho odstavce")
deDE("Absätze zusammenfassen")
frFR("Fusionner en un paragraphe")
huHU("Egyszerű bekezdéshez")
itIT("Paragrafo singolo")
plPL("Do pojedynczego paragrafu")
ruRU("В один параграф")
srSP("Ka jednom paragrafu")

T_("Undo")
csCZ("Zpět")
deDE("Rückgängig")
frFR("Annuler")
huHU("Visszavonás")
itIT("Annulla")
plPL("Cofnij")
ruRU("Отменить")
srSP("Undo")

T_("Redo")
csCZ("Znovu")
deDE("Wiederherstellen")
frFR("Refaire")
huHU("Újra végrehajtás")
itIT("Ripeti")
plPL("Powtórz")
ruRU("Повторить")
srSP("Redo")

T_("Cut")
csCZ("Vyjmout")
deDE("Ausschneiden")
frFR("Couper")
huHU("Kivágás")
itIT("Taglia")
plPL("Wytnij")
ruRU("Вырезать")
srSP("Iseci")

T_("Copy")
csCZ("Kopírovat")
deDE("Kopieren")
frFR("Copier")
huHU("Másolás")
itIT("Copia")
plPL("Kopiuj")
ruRU("Копировать")
srSP("Kopiraj")

T_("Paste")
csCZ("Vložit")
deDE("Einfügen")
frFR("Coller")
huHU("Beillesztés")
itIT("Incolla")
plPL("Wklej")
ruRU("Вставить")
srSP("Zalepi")

T_("Print")
csCZ("Tisk")
deDE("Drucken")
frFR("Imprimer")
huHU("Nyomtatás")
itIT("Stampa")
plPL("Drukuj")
ruRU("Печать")
srSP("Štampa")

T_("Find/Replace")
csCZ("Vyhledat/Nahradit")
deDE("Suchen/Ersetzen")
frFR("Chercher/Remplacer")
huHU("Keresés/Csere")
itIT("Trova/Sostituisci")
plPL("Znajdź/Zamień")
ruRU("Найти/Заменить")
srSP("Pronađi/Zameni")

T_("Insert table..")
csCZ("Vložit tabulku..")
deDE("Tabelle einfügen ...")
frFR("Insérer un tableau..")
huHU("Táblázat beszútása")
itIT("Inserisci tabella..")
plPL("Wstaw tabelę..")
ruRU("Вставить таблицу")
srSP("Ubaci tabelu..")

T_("Table properties..")
csCZ("Vlastnosti tabulky..")
deDE("Tabelleneigenschaften ...")
frFR("Propriétés du tableau..")
huHU("Táblázat tulajdonságai")
itIT("Propriet� tabella..")
plPL("Właściwości tabeli..")
ruRU("Свойства таблицы")
srSP("Svojstva tabele..")

T_("Insert row")
csCZ("Vložit řádek")
deDE("Zeile einfügen")
frFR("Insérer une ligne")
huHU("Sor beszúrása")
itIT("Inserisci riga")
plPL("Wstaw wiersz")
ruRU("Вставить ряд")
srSP("Ubaci red")

T_("Remove row")
csCZ("Odstranit řádek")
deDE("Zeile entfernen")
frFR("Supprimer la ligne")
huHU("Sor törlése")
itIT("Rimuovi riga")
plPL("Usuń wiersz")
ruRU("Удалить ряд")
srSP("Ukloni red")

T_("Insert column")
csCZ("Vložit sloupec")
deDE("Spalte einfügen")
frFR("Insérer une colonne")
huHU("Oszlop beszúrása")
itIT("Inserisci colonna")
plPL("Wstaw kolumnę")
ruRU("Вставить колонку")
srSP("Ubaci kolonu")

T_("Remove column")
csCZ("Odstranit sloupec")
deDE("Spalte entfernen")
frFR("Supprimer la colonne")
huHU("Oszlop törlése")
itIT("Rimuovi colonna")
plPL("Usuń kolumnę")
ruRU("Удалить колонку")
srSP("Ukloni kolonu")

T_("Join cells")
csCZ("Spojit buňky")
deDE("Zellen verbinden")
frFR("Fusionner les cellules")
huHU("Mezők egyesítése")
itIT("Unisci celle")
plPL("Scal komórki")
ruRU("Объединить ячейки")
srSP("Spoji ćelije")

T_("Split cell..")
csCZ("Rozdělit buňku")
deDE("Zelle teilen ...")
frFR("Diviser la cellule..")
huHU("Mező felosztása..")
itIT("Dividi cella..")
plPL("Podziel komórkę..")
ruRU("Разбить ячейки...")
srSP("Podeli ćeliju..")

T_("Cell properties..")
csCZ("Vlastnosti buňky..")
deDE("Zelleigenschaften ...")
frFR("Propriétés de la cellule")
huHU("Mező tulajdonságok..")
itIT("Propriet� celle..")
plPL("Właściwości komórki")
ruRU("Свойства ячейки...")
srSP("Svojstva ćelije..")


// RichEdit.lay

T_("Alignment")
csCZ("&Zarovnat:")
deDE("Ausrichtung")
frFR("Alignement")
huHU("Igazítás")
itIT("Allineamento")
plPL("Wyrównanie")
ruRU("Выравнивание")
srSP("Poravnanje:")

T_("Left\nCenter\nRight\nJustify")
csCZ("Vlevo\nStřed\nVpravo\nDo bloku")
deDE("Links\nMitte\nRechts\nBlocksatz")
frFR("Gauche\nCentrer\nDroite\nJustifier")
huHU("Bal\nKözép\nJobb\nMargó")
itIT("Sinistra\nCentro\nDestra\nGiustificato")
plPL("Do lewej\nWyśrodkowane\nDo prawej\nWyjustowane")
ruRU("Влево\nПо центру\nВправо\nПо ширине")
srSP("Levo\nPo sredini\nDesno\nporavnato")

T_("Before")
csCZ("Před")
deDE("Vorher")
frFR("Avant")
huHU("Előtte")
itIT("Prima")
plPL("Przed")
ruRU("Перед")
srSP("Pre")

T_("After")
csCZ("Po")
deDE("Danach")
frFR("Après")
huHU("Utána")
itIT("Dopo")
plPL("Po")
ruRU("После")
srSP("Posle")

T_("Left margin")
csCZ("Levý okraj")
deDE("Linker Rand")
frFR("Marge de gauche")
huHU("Bal szegély")
itIT("Margine sinistro")
plPL("Lewy margines")
ruRU("Поле слева")
srSP("Leva margina")

T_("ParaLayout_rm_1_SetLabel\aRight margin")
csCZ("Pravý okraj")
deDE("ParaLayout_rm_1_SetLabel\aRechter Rand")
frFR("")
huHU("")
itIT("ParaLayout_rm_1_SetLabel\aMargine destro")
plPL("Prawy margines")
ruRU("")
srSP("")

T_("Indent")
csCZ("O&dsazení:")
deDE("Einrücken")
frFR("Indenter")
huHU("Behúzás")
itIT("Indent")
plPL("Wcięcie")
ruRU("Отступ")
srSP("")

T_("Break page before")
csCZ("&Zalomit stránku před")
deDE("Seitenumbruch vorher")
frFR("Saut de page avant")
huHU("Oldaltörés előtte")
itIT("Precedi interruzione pagina")
plPL("Załam stronę przed")
ruRU("Оборвать страницу после")
srSP("Prelomi stranu pre")

T_("Keep together")
csCZ("&Svázat řádky")
deDE("Zusammenhalten")
frFR("Garder assemblé")
huHU("Együtt tartás")
itIT("Mantieni assieme")
plPL("Trzymaj razem")
ruRU("Держать вместе")
srSP("Drži zajedno")

T_("Keep with next")
csCZ("Svázat s &následujícím")
deDE("Zusammen mit nächstem")
frFR("Assembler au suivant")
huHU("Marad a következővel")
itIT("Mantieni col successivo")
plPL("Trzymaj z następną")
ruRU("Придерживаться следующего")
srSP("Drži sa sledećim")

T_("Allow orphans")
csCZ("Povolit osa&mocené řádky")
deDE("Schusterjungen zulassen")
frFR("Autoriser les orphelines")
huHU("Árvák megengedése")
itIT("Consenti isolati")
plPL("Dopuszczaj sieroty")
ruRU("Разрешить висячие строки")
srSP("Dozvoli siročiće")

T_("Default tab size")
csCZ("Výchozí tabelace")
deDE("Voreingestellte Tabulatorweite")
frFR("Tabulation par défaut")
huHU("Alapértelmezett tabulátorméret")
itIT("Dimensione tabulatore predefinita")
plPL("Domyślny rozmiar tabulacji")
ruRU("Размер табуляции по умолчанию")
srSP("Podrazumevana veličina tabulatora")

T_("Bullet")
csCZ("Odrážka")
deDE("Aufzählungszeichen")
frFR("Puce")
huHU("korong")
itIT("Elenco puntato")
plPL("Wypunktowanie")
ruRU("Списочный маркер")
srSP("Označavanje")

T_("Before number")
csCZ("Před číslem")
deDE("Vor der Nummer")
frFR("Nombre avant")
huHU("Szám előtte")
itIT("Numero prima")
plPL("Przed numerem")
ruRU("Перед числом")
srSP("Pre broja")

T_("After number")
csCZ("Po čísle")
deDE("Nach der Nummer")
frFR("Nombre après")
huHU("Szám utána")
itIT("Numero successivo")
plPL("Po numerze")
ruRU("После числа")
srSP("Posle broja")

T_("Reset")
csCZ("Nulovat")
deDE("Zurücksetzen")
frFR("Réinitialiser")
huHU("Kiinduló állapot")
itIT("Azzera")
plPL("Przywróć")
ruRU("Сбросить")
srSP("Vrati")

T_("Numbering")
csCZ("Číslování")
deDE("Nummerierung")
frFR("Numérotation")
huHU("Számozás")
itIT("Numerazione")
plPL("Numerowanie")
ruRU("Нумерование")
srSP("Nabrajanje")

T_("Text flow")
csCZ("Tok textu")
deDE("Textfluss")
frFR("Flux du texte")
huHU("Szöveg körbefolyatás")
itIT("Flusso testo")
plPL("Przepływ tekstu")
ruRU("Расположение текста")
srSP("Tok teksta")

T_("Layout")
csCZ("Rozvržení")
deDE("Layout")
frFR("Agencement")
huHU("Elrendezés")
itIT("Layout")
plPL("Rozkład")
ruRU("Раскладка")
srSP("Raspored")

T_("Tabs")
csCZ("Tabelace")
deDE("Tabulatoren")
frFR("Tabulations")
huHU("Tabulátorok")
itIT("Tabulatori")
plPL("Tabulatory")
ruRU("Табуляторы")
srSP("Tabulatori")

T_("dot\npoint\ninch\nmm\ncm")
csCZ("dot\nbod\npalec\nmm\ncm")
deDE("Pixel\nPunkt\nZoll\nmm\ncm")
frFR("pica\npoint\npouce\nmm\ncm")
huHU("képpont\npont\nhüvelyk\nmm\ncm")
itIT("dot\npunti\npollici\nmm\ncm")
plPL("punkty\npiksele\ncale\nmm\ncm")
ruRU("точки\nпоинты\nдюймы\nмм\nсм")
srSP("tačka\npoint\ninč\nmm\ncm")

T_("Reveal codes")
csCZ("Pomocné znaky")
deDE("Steuerzeichen anzeigen")
frFR("Texte masqué")
huHU("Kódok megjelenítése")
itIT("Visualizza codici")
plPL("Niewidoczne znaki")
ruRU("Показать коды")
srSP("Pokaži kod")

T_("Zoom")
csCZ("Zmenšit")
deDE("Zoom")
frFR("Zoom")
huHU("Nagyítás")
itIT("Zoom")
plPL("Powiększenie")
ruRU("Увеличить")
srSP("Uveličaj")

T_("OK")
csCZ("OK")
deDE("OK")
frFR("Ok")
huHU("Rendben")
itIT("Ok")
plPL("OK")
ruRU("OK")
srSP("OK")

T_("Cancel")
csCZ("Storno")
deDE("Abbrechen")
frFR("Annuler")
huHU("Mégsem")
itIT("Annulla")
plPL("Anuluj")
ruRU("Отмена")
srSP("Otkaži")

T_("New")
csCZ("Nový")
deDE("Neu")
frFR("Nouveau")
huHU("Új")
itIT("Nuovo")
plPL("Nowy")
ruRU("Новый")
srSP("Novi")

T_("Wi&dth:")
csCZ("&Šířka")
deDE("&Breite")
frFR("La&rgeur :")
huHU("&Szélesség:")
itIT("La&rghezza:")
plPL("Szero&kość:")
ruRU("&Ширина:")
srSP("&Širina")

T_("H&eight:")
csCZ("&Výška")
deDE("&Höhe")
frFR("H&auteur :")
huHU("&Magasság:")
itIT("A&ltezza")
plPL("Wysok&ość:")
ruRU("&Высота:")
srSP("&Visina")

T_("&Width (%):")
csCZ("Šíř&ka (%):")
deDE("B&reite (%)")
frFR("&Largeur (%) :")
huHU("S&zélesség (%):")
itIT("&Larghezza (%):")
plPL("&Szerokość (%):")
ruRU("&Ширина (%):")
srSP("&Širina (%):")

T_("Height (%):")
csCZ("Výška (%):")
deDE("H&öhe (%)")
frFR("Hauteur (%) :")
huHU("Magasság (%):")
itIT("Altezza (%):")
plPL("Wysokość (%):")
ruRU("Высота (%):")
srSP("&Visina (%):")

T_("&Descent:")
csCZ("&Zanoření")
deDE("&Unterlänge")
frFR("&Descente :")
huHU("&Csökkenés:")
itIT("&Diminuisci:")
plPL("&Pochyłość")
ruRU("&Наклон:")
srSP("&Nagib:")

T_("Keep aspect ratio")
csCZ("Zachovat poměr")
deDE("Seitenverhältnis beibehalten")
frFR("Garder les proportions")
huHU("Méretarány megtartása")
itIT("Mantieni proporzioni")
plPL("Zachowuj stosunek szerokości do wysokości")
ruRU("Сохранять пропорции")
srSP("Zadrži razmeru")

T_("Font")
csCZ("Písmo")
deDE("Schriftart")
frFR("Police")
huHU("Font")
itIT("Carattere")
plPL("Czcionka")
ruRU("Шрифт")
srSP("Font")

T_("Height")
csCZ("Výška")
deDE("Schriftgrad")
frFR("Hauteur")
huHU("Magasság")
itIT("Altezza")
plPL("Wysokość")
ruRU("Высота")
srSP("Visina")

T_("Ink")
csCZ("Text")
deDE("Textfarbe")
frFR("Encre")
huHU("Tinta")
itIT("Testo")
plPL("Kolor tekstu")
ruRU("Чернила")
srSP("Tinta")

T_("Paper")
csCZ("Papír")
deDE("Hintergrundfarbe")
frFR("Papier")
huHU("Papír")
itIT("Sfondo")
plPL("Kolor tła")
ruRU("Бумага")
srSP("Papir")

T_("Style of next paragraph")
csCZ("Styl následujícího odstavce")
deDE("Stil des folgenden Absatzes")
frFR("Style du paragraphe suivant")
huHU("Következő bekezdés stílusa")
itIT("Stile paragrafo successivo")
plPL("Styl następnego paragrafu")
ruRU("Стиль следующего параграфа")
srSP("Stil sledećeg paragrafa")

T_("Character")
csCZ("Znaky")
deDE("Zeichen")
frFR("Caractère")
huHU("Karakter")
itIT("Carattere")
plPL("Znak")
ruRU("Символ")
srSP("Karakter")

T_("&Find:")
csCZ("&Vyhledat")
deDE("&Suchen:")
frFR("&Rechercher :")
huHU("&Keresés:")
itIT("&Trova:")
plPL("&Znajdź:")
ruRU("&Найти:")
srSP("&Pronađi:")

T_("&Replace:")
csCZ("&Nahradit")
deDE("&Ersetzen:")
frFR("&Remplacer :")
huHU("&Csere:")
itIT("&Sostituisci:")
plPL("&Zamień:")
ruRU("&Заменить:")
srSP("&Zameni:")

T_("&Whole word")
csCZ("&Celé slovo")
deDE("Ganzes &Wort")
frFR("&Mot entier")
huHU("&Egész szó")
itIT("")
plPL("&Całe słowo")
ruRU("&Слово целиком")
srSP("&Cela reč")

T_("&Ignore case")
csCZ("&Ignorovat velikost písma")
deDE("&Groß-/Kleinschreibung ignorieren")
frFR("&Ignorer la casse")
huHU("&Nagybetűk figyelmen kívül")
itIT("Ignora maiuscole/minuscole")
plPL("Ignoruj wielkość liter")
ruRU("&Игнорировать регистр")
srSP("&Ignoriši mala/velika slova")

T_("&Replace")
csCZ("N&ahradit")
deDE("&Ersetzen")
frFR("&Remplacer")
huHU("&Csere")
itIT("&Sostituisci")
plPL("&Zamień")
ruRU("&Заменить")
srSP("&Zameni")

T_("Header")
csCZ("Záhlaví")
deDE("Überschrift")
frFR("En-tête")
huHU("Fejléc")
itIT("Intestazione")
plPL("Nagłówek")
ruRU("Заголовок")
srSP("Zaglavlje")

T_("Number of columns")
csCZ("Počet sloupců")
deDE("Anzahl der Spalten")
frFR("Nombre de colonnes")
huHU("Oszlopok száma")
itIT("Numero di colonne")
plPL("Liczba kolumn")
ruRU("Число столбцов")
srSP("BRoj kolona")

T_("Right margin")
csCZ("Pravý okraj")
deDE("Rechter Rand")
frFR("Marge de droite")
huHU("Jobb szegély")
itIT("Margine destro")
plPL("Prawy margines")
ruRU("Поле справа")
srSP("Desna margina")

T_("Frame")
csCZ("Rámeček")
deDE("Rahmen")
frFR("Cadre")
huHU("Keret")
itIT("Riquadro")
plPL("Obramowanie")
ruRU("Рамка")
srSP("Okvir")

T_("color")
csCZ("barva")
deDE("Farbe")
frFR("couleur")
huHU("szín")
itIT("Colore")
plPL("kolor")
ruRU("цвет")
srSP("boja")

T_("Grid")
csCZ("Mřížka")
deDE("Gitternetz")
frFR("grille")
huHU("Illesztőrács")
itIT("Griglia")
plPL("Siatka")
ruRU("Сетка")
srSP("Mreža")

T_("Equalize")
csCZ("Vyrovnat")
deDE("Angleichen")
frFR("Egaliser")
huHU("Kiegyenlítés")
itIT("Equalizza")
plPL("Wyrównaj")
ruRU("")
srSP("Izjednači")

T_("Remove table")
csCZ("Odstranit tabulku")
deDE("Tabelle entfernen")
frFR("Supprimer le tableau")
huHU("Táblázat törlése")
itIT("Rimuovi tabella")
plPL("Usuń tabelę")
ruRU("Удалить таблицу")
srSP("Ukloni tabelu")

T_("Horizontal")
csCZ("Vodorovně")
deDE("Horizontal")
frFR("Horizontal")
huHU("Vízszintes")
itIT("Orizzontale")
plPL("Poziomy")
ruRU("Горизонтально")
srSP("Horizontalno")

T_("Vertical")
csCZ("Svisle")
deDE("Vertikal")
frFR("Vertical")
huHU("Függőleges")
itIT("Verticale")
plPL("Pionowy")
ruRU("Вертикально")
srSP("Vertikalno")

T_("Borders")
csCZ("Ohraničení")
deDE("Rahmen")
frFR("Bordures")
huHU("Határvonalak")
itIT("Bordi")
plPL("Ramki")
ruRU("Рамки")
srSP("Granice")

T_("Top")
csCZ("Nahoře")
deDE("Oben")
frFR("Haut")
huHU("Felső szél")
itIT("Alto")
plPL("Góra")
ruRU("Верх")
srSP("Vrh")

T_("Bottom")
csCZ("Dole")
deDE("Unten")
frFR("Base")
huHU("Alsó szél")
itIT("Basso")
plPL("Dół")
ruRU("Низ")
srSP("Dno")

T_("Margins")
csCZ("Okraje")
deDE("Ränder")
frFR("Marges")
huHU("Margók")
itIT("Margini")
plPL("Marginesy")
ruRU("Поля")
srSP("Margine")

T_("Align")
csCZ("Zarovnání")
deDE("Ausrichten")
frFR("Aligner")
huHU("Igazítás")
itIT("Allinea")
plPL("Wyrównanie")
ruRU("Выровнять")
srSP("Poravnanje")

T_("Top\nCenter\nBottom")
csCZ("Horní okraj\nStřed\nDolní okraj")
deDE("Oben\nMitte\nUnten")
frFR("Haut\nCentrer\nBas")
huHU("Felülre\nKözépre\nAlulra")
itIT("Ato\nCentro\nBasso")
plPL("Góra\nŚrodek\nDół")
ruRU("Верх\nЦентр\nНиз")
srSP("Vrh\nSredina\nDno")

T_("Border")
csCZ("Ohraničení")
deDE("Rahmen")
frFR("Bordure")
huHU("Határvonal")
itIT("Bordo")
plPL("Ramka")
ruRU("Рамка")
srSP("Granica")

T_("Background")
csCZ("Pozadí")
deDE("Hintergrund")
frFR("Arrière-plan")
huHU("Háttér")
itIT("Sfondo")
plPL("TŁo")
ruRU("Цвет фона")
srSP("Pozadina")

T_("Minimal height")
csCZ("Minimální výška")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")

T_("Keep with next line")
csCZ("Svázat s následujícím řádkem")
deDE("Mit nächster Zeile zusammenhalten")
frFR("Garder pour la prochaine ligne")
huHU("Következő sorral tartás")
itIT("Mantieni con la riga successiva")
plPL("Trzymaj z następną linią")
ruRU("Придерживаться следующей линии")
srSP("Drži sa sledećom linijom")
