
// EditCtrl.h

T_("(default)")
csCZ("(výchozí)")
deDE("(Voreinstellung)")
frFR("")
huHU("")
itIT("(predefinito)")
plPL("(domyślny)")
ruRU("")
srSP("")
zhCN("(缺省)")


// EditField.cpp

T_("Undo")
csCZ("Zpět")
deDE("Rückgängig")
frFR("Annuler")
huHU("Visszavonás")
itIT("Annulla")
plPL("Cofnij")
ruRU("Отменить")
srSP("Undo")
zhCN("撤销")

T_("Cut")
csCZ("Vyjmout")
deDE("Ausschneiden")
frFR("Couper")
huHU("Kivágás")
itIT("Taglia")
plPL("Wytnij")
ruRU("Вырезать")
srSP("Iseci")
zhCN("剪切")

T_("Copy")
csCZ("Kopírovat")
deDE("Kopieren")
frFR("Copier")
huHU("Másolás")
itIT("Copia")
plPL("Kopiuj")
ruRU("Копировать")
srSP("Kopiraj")
zhCN("复制")

T_("Paste")
csCZ("Vložit")
deDE("Einfügen")
frFR("Coller")
huHU("Beillesztés")
itIT("Incolla")
plPL("Wklej")
ruRU("Вставить")
srSP("Zalepi")
zhCN("粘贴")

T_("Erase")
csCZ("Vymazat")
deDE("Löschen")
frFR("Effacer")
huHU("Törlés")
itIT("Cancella")
plPL("Usuń")
ruRU("Стереть")
srSP("Obriši")
zhCN("清除")

T_("Select all")
csCZ("Vybrat vše")
deDE("Alles auswählen")
frFR("Tout sélectionner")
huHU("Minden kiválasztása")
itIT("Seleziona tutto")
plPL("Zaznacz wszystko")
ruRU("Выделить всё")
srSP("Izaberi sve")
zhCN("全选")


// Text.cpp

T_("Redo")
csCZ("Znovu")
deDE("Wiederherstellen")
frFR("Refaire")
huHU("Újra végrehajtás")
itIT("Ripeti")
plPL("Powtórz")
ruRU("Повторить")
srSP("Redo")
zhCN("重做")


// ArrayCtrl.cpp

T_("Do you really want to delete the selected %s ?")
csCZ("Smazat aktuální %s ?")
deDE("Möchten Sie die ausgewählte %s wirklich löschen?")
frFR("Voulez-vous réellement supprimer le %s sélectioné ?")
huHU("Biztosan töröljük a kijelölt %s ?")
itIT("Vuoi realmente cancellare la %s selezionata ?")
plPL("Czy na pewno chcesz usunąć zaznaczone %s ?")
ruRU("Вы действительно хотите удалить выделенный "
     "%s?")
srSP("Da li stvarno želite da obrišete izabran %s?")
zhCN("真的要删除选择的 %s 吗? ")

T_("Insert %s")
csCZ("Vložit %s")
deDE("%s einfügen")
frFR("Insérer %s")
huHU("Beszúrás")
itIT("Inserisci %s")
plPL("Wstaw %s")
ruRU("Вставить %s")
srSP("Ubaci %s")
zhCN("插入 %s")

T_("Insert a new %s into the table.")
csCZ("Vložit do tabulky nový %s.")
deDE("Neue %s in die Tabelle einfügen")
frFR("Insère une nouvelle %d dans la table.")
huHU("Új %s beszúrása a táblázatba")
itIT("Inserisce una nuova %s nella tabella.")
plPL("Wstawia nowy %s do tabeli.")
ruRU("Вставить новый %s в таблицу.")
srSP("Ubaci u tabelu novi %s.")
zhCN("插入新的 %s 到表格")

T_("Insert %s before")
csCZ("Vložit %s před")
deDE("%s vorher einfügen")
frFR("Insérer %s avant")
huHU("%s beszúrása elé")
itIT("Inserisci %s sopra")
plPL("Wstaw %s przed")
ruRU("Вставить %s перед")
srSP("Ubaci %s pre")
zhCN("前插 %s")

T_("Insert a new %s into the table before the actual one")
csCZ("Vložit nový %s před aktuální")
deDE("Neue %s vor der aktuellen in die Tabelle einfügen")
frFR("Insérer une nouvelle %d dans la table avant l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
itIT("Inserisce una nuova %s prima di quella selezioanta")
plPL("Wstawia nowy %s do tabeli przed aktualnym")
ruRU("Вставить новый %s в таблицу перед существующим")
srSP("Ubaci novi %s u tabeli pre trenutne")
zhCN("在表格中当前项前插入新的 %s")

T_("Insert %s after")
csCZ("Vložit %s za")
deDE("%s danach einfügen")
frFR("Insérer %s après")
huHU("% beszúrása mögé")
itIT("Inserisci %s sotto")
plPL("Wstaw %s po")
ruRU("Вставить %s после")
srSP("Ubaci %s posle")
zhCN("后插 %s")

T_("Insert a new %s into the table after the actual one")
csCZ("Vložit %s za aktuální")
deDE("Neue %s hinter der aktuellen in die Tabelle einfügen")
frFR("Insérer une nouvelle %d dans la table après l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
itIT("Inserisce una nuova %s dopo quella selezioanta")
plPL("Wstawia nowy %s do tabeli po aktualnym")
ruRU("Вставить новый %s в таблицу после существующего")
srSP("Ubaci novi %s u tabeli posle trenutne")
zhCN("在表格中当前项后插入新的 %s")

T_("Append %s")
csCZ("Přidat %s")
deDE("%s hinzufügen")
frFR("Ajouter %s")
huHU("%s hozzáfűzése")
itIT("Aggiungi %s")
plPL("Dodaj %s")
ruRU("Добавить %s")
srSP("Dodaj %s")
zhCN("添加 %s")

T_("Append a new %s at the end of the table.")
csCZ("Přidat nový %s na konec")
deDE("Neue %s am Ende der Tabelle hinzufügen")
frFR("Ajouter une nouvelle %s à la fin de la table.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
itIT("Aggiunge una nuova %s al fondo della tabella.")
plPL("Dodaje nowy %s na końcu tabeli.")
ruRU("Добавить новый %s в конце таблицы.")
srSP("Dodaj novi %s na kraju tabele.")
zhCN("在表格末尾插入新的 %s")

T_("Duplicate %s")
csCZ("Duplikovat %s")
deDE("%s duplizieren")
frFR("Dupliquer %s")
huHU("%s megkettőzése")
itIT("Duplica %s")
plPL("Zduplikuj %s")
ruRU("Дублировать %s")
srSP("Dupliraj %s")
zhCN("复制 %s")

T_("Duplicate current table %s.")
csCZ("Vložit do tabulky duplikát aktuálního %s.")
deDE("Aktuelle %s der Tabelle duplizieren")
frFR("Dupliquer la table %s sélectionnée.")
huHU("Az aktuális táblázat megkettőzése")
itIT("Duplica la tabella %s selezionata.")
plPL("Utwórz duplikat aktualnej tabeli %s.")
ruRU("Дублировать текущий %s таблицы.")
srSP("Dupliraj trenutni %s tabele.")
zhCN("复制当前表格 %s.")

T_("Edit %s")
csCZ("Opravit aktuální %s")
deDE("%s bearbeiten")
frFR("Editer %s")
huHU("%s szerkesztése")
itIT("Edita %s")
plPL("Edytuj %s")
ruRU("Редактировать %s")
srSP("Promeni %s")
zhCN("编辑 %s")

T_("Edit active %s.")
csCZ("Opravit aktuální %s.")
deDE("Aktive %s bearbeiten")
frFR("Editer %s actif.")
huHU("Az aktuális %s szerkesztése")
itIT("Edita la %s attiva.")
plPL("Edytowanie aktualnego %s.")
ruRU("Редактировать активный %s.")
srSP("Promeni aktivni %s.")
zhCN("编辑活动 %s")

T_("Delete %s\tDelete")
csCZ("Odstranit %s\tDelete")
deDE("%s löschen\tLöschen")
frFR("Supprimer %s\tSupprimer")
huHU("Törlés %s\tTörlés")
itIT("Cancella %s\tCancella")
plPL("Usuń %s\tUsuń")
ruRU("Удалить %s\tУдалить")
srSP("Obriši %s\tObriši")
zhCN("删除%s\t删除")

T_("Delete active %s.")
csCZ("Odstranit aktuální %s.")
deDE("Aktive %s löschen")
frFR("Supprimer %s actif.")
huHU("Az aktív %s törlése")
itIT("Cancella %s attiva.")
plPL("Usuwa aktualny %s.")
ruRU("Удалить активный %s.")
srSP("Obriši aktivni %s.")
zhCN("删除活动 %s")

T_("Move %s up")
csCZ("Posunout %s nahoru")
deDE("%s nach oben verschieben")
frFR("Monter %s")
huHU("%s felfelé mozgatása")
itIT("Sposta %s su")
plPL("Przesuń %s do góry")
ruRU("Двигать %s вверх")
srSP("Pomeri %s na gore")
zhCN("上移%s")

T_("Swap %s with previous thus moving it up.")
csCZ("Vyměnit aktuální %s s předchozím a tak ho posunout nahoru.")
deDE("%s mit der vorigen vertauschen und so nach oben verschieben")
frFR("Intervertir %s avec le précédent.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
itIT("Inverte la %s con la precedente.")
plPL("Zamienia %s z poprzednim przesuwając go do góry.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")
srSP("Zameni %s sa prethodnim, pomeri ga na gore.")
zhCN("将%s与前面换位上移之")

T_("Move %s down")
csCZ("Posunout %s dolů")
deDE("%s nach unten verschieben")
frFR("Descendre %s")
huHU("%s lefelé mozgatása")
itIT("Sposta %s giu")
plPL("Przesuń %s w dół")
ruRU("Двигать %s вниз")
srSP("Pomeri %s dole")
zhCN("下移%s")

T_("Swap %s with next thus moving it down.")
csCZ("Vyměnit aktuální %s s dalším a tak ho posunout dolů.")
deDE("%s mit der nächsten vertauschen und so nach unten verschieben")
frFR("Intervertir %s avec le suivant.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
itIT("Inverte la %s la successiva.")
plPL("Zamienia %s z następnym przesuwając go w dół.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")
srSP("Zameni %s sa sledećim, pomeri ga na dole.")
zhCN("将%s与后面换位下移之")

T_("Select all table rows")
csCZ("Vybrat všechny řádky v tabulce")
deDE("Alle Zeilen der Tabelle auswählen")
frFR("Sélectionner toutes les lignes")
huHU("Az összes sor kijelölése")
itIT("Seleziona tutte le righe")
plPL("Zaznacz wszystkie wiersze tabeli")
ruRU("Выделить все ряды таблицы")
srSP("Izaberi sve redove tabele")
zhCN("全选表格行")

T_("row")
csCZ("řádek")
deDE("Zeile")
frFR("ligne")
huHU("sor")
itIT("riga")
plPL("wiersz")
ruRU("ряды")
srSP("red")
zhCN("行")


// Progress.cpp

T_("Working...")
csCZ("Pracuji...")
deDE("Bearbeitung läuft ...")
frFR("En cours d'exécution...")
huHU("Folyamatban...")
itIT("Esecuzione...")
plPL("Pracuję...")
ruRU("Обработка...")
srSP("Radim...")
zhCN("工作中...")


// AKeys.cpp

T_("Setup keys")
csCZ("Nastavit klávesy")
deDE("Tasten zuweisen")
frFR("Configurer les raccourcis")
huHU("Billentyűk beállítása")
itIT("Selezione tasti veloci")
plPL("Ustawienia klawiszy")
ruRU("")
srSP("Podesi tastere")
zhCN("设置键值")

T_("Group")
csCZ("Skupina")
deDE("Gruppe")
frFR("Groupe")
huHU("Csoport")
itIT("Gruppo")
plPL("Grupa")
ruRU("")
srSP("Grupa")
zhCN("组")

T_("Action")
csCZ("Akce")
deDE("Aktion")
frFR("Action")
huHU("Művelet")
itIT("Azione")
plPL("Akcja")
ruRU("")
srSP("Akcija")
zhCN("动作")

T_("Key 1")
csCZ("Klávesa 1")
deDE("Taste 1")
frFR("Touche 1")
huHU("1. billentyű")
itIT("Combinazione 1")
plPL("Klawisz 1")
ruRU("")
srSP("Taster 1")
zhCN("键1")

T_("Key 2")
csCZ("Klávesa 2")
deDE("Taste 2")
frFR("Touche 2")
huHU("2. billentyű")
itIT("Combinazione 2")
plPL("Klawisz 2")
ruRU("")
srSP("Taster 2")
zhCN("键2")


// Prompt.cpp

T_("OK")
csCZ("OK")
deDE("OK")
frFR("Ok")
huHU("Rendben")
itIT("Ok")
plPL("OK")
ruRU("OK")
srSP("OK")
zhCN("确定")

T_("Cancel")
csCZ("Storno")
deDE("Abbrechen")
frFR("Annuler")
huHU("Mégsem")
itIT("Annulla")
plPL("Anuluj")
ruRU("Отмена")
srSP("Otkaži")
zhCN("取消")

T_("&Yes")
csCZ("&Ano")
deDE("&Ja")
frFR("&Oui")
huHU("&Igen")
itIT("&Si")
plPL("&Tak")
ruRU("&Да")
srSP("&Da")
zhCN("是(&Y)")

T_("&No")
csCZ("&Ne")
deDE("&Nein")
frFR("&Non")
huHU("&Nem")
itIT("&No")
plPL("&Nie")
ruRU("&Нет")
srSP("&Ne")
zhCN("否(&N)")

T_("&Abort")
csCZ("&Přerušit")
deDE("&Abbrechen")
frFR("&Interrompre")
huHU("&Megszakítás")
itIT("&Interrompi")
plPL("&Przerwij")
ruRU("&Прервать")
srSP("&Prekini")
zhCN("放弃(&A)")

T_("&Retry")
csCZ("&Opakovat")
deDE("&Erneut versuchen")
frFR("&Réessayer")
huHU("&Újra")
itIT("&Riprova")
plPL("Po&wtórz")
ruRU("П&овторить")
srSP("&Ponovi")
zhCN("重试(&R)")

T_("&Cancel")
csCZ("&Zrušit")
deDE("&Abbrechen")
frFR("&Annuler")
huHU("Mégsem")
itIT("&Annulla")
plPL("&Anuluj")
ruRU("&Отменить")
srSP("&Otkaži")
zhCN("取消(&C)")


// Help.cpp

T_("Go Back")
csCZ("Předchozí téma")
deDE("Rückwärts")
frFR("Précédent")
huHU("Visszalépés")
itIT("Indiatro")
plPL("Idź wstecz")
ruRU("Назад")
srSP("Nazad")
zhCN("回退")

T_("Go Forward")
csCZ("Další téma")
deDE("Vorwärts")
frFR("Suivant")
huHU("Előrelépés")
itIT("Avanti")
plPL("Idź do przodu")
ruRU("Вперёд")
srSP("Napred")
zhCN("向前")

T_("Font size")
csCZ("Velikost")
deDE("Schriftgrad")
frFR("Taille de police")
huHU("Betűméret")
itIT("Dimensione font")
plPL("Rozmiar czcionki")
ruRU("Размер шрифта")
srSP("Veličina fonta")
zhCN("字体大小")

T_("Print")
csCZ("Tisk")
deDE("Drucken")
frFR("Imprimer")
huHU("Nyomtatás")
itIT("Stampa")
plPL("Drukuj")
ruRU("Печать")
srSP("Štampa")
zhCN("打印")

T_("Help")
csCZ("Nápověda")
deDE("Hilfe")
frFR("Aide")
huHU("Súgó")
itIT("Aiuto")
plPL("Pomoc")
ruRU("Помощь")
srSP("Pomoć")
zhCN("帮助")


// StatusBar.cpp

T_("Ready")
csCZ("Připraven")
deDE("Fertig")
frFR("Prêt")
huHU("Kész")
itIT("Pronto")
plPL("Gotowy")
ruRU("Готов")
srSP("Spreman")
zhCN("待命")


// TabCtrl.cpp

T_("Apply")
csCZ("Použít")
deDE("Übernehmen")
frFR("Appliquer")
huHU("")
itIT("Applica")
plPL("Zastosuj")
ruRU("")
srSP("Primeni")
zhCN("应用")

T_("Close")
csCZ("Zavřít")
deDE("Schließen")
frFR("Fermer")
huHU("")
itIT("Chiudi")
plPL("Zamknij")
ruRU("")
srSP("Zatvori")
zhCN("关闭")


// DlgColor.cpp

T_("(no color)")
csCZ("(bez barvy)")
deDE("(keine Farbe)")
frFR("(aucune couleur)")
huHU("(nincs szín)")
itIT("(nessun colore)")
plPL("(bez koloru)")
ruRU("нет цвета")
srSP("(bez boje)")
zhCN("(无颜色)")

T_("Set color")
csCZ("Nastavit barvu")
deDE("Farbe festlegen")
frFR("Appliquer la couleur")
huHU("Szín beállítása")
itIT("(Set colore)")
plPL("(Ustaw kolor)")
ruRU("Установить цвет")
srSP("Postavi boju")
zhCN("设置颜色")

T_("Write current color to selected palette slot")
csCZ("Nastavit barvu pole v paletě na aktuální kreslicí barvu")
deDE("Palettenplatz mit aktueller Farbe belegen")
frFR("Ecrire la couleur courante dans l'emplacement sélectionné de la palette")
huHU("Aktuális szín beírása a kijelölt palettamezőbe")
itIT("Salva il colore corrente nello slot selezionato della tavolozza")
plPL("Zapisz aktualny kolor do wskazanego miejsca w palecie kolorów")
ruRU("Записать текущий цвет в выделенный слот "
     "палитры")
srSP("Zapiši trenutnu boju u izabranu paletu boja")
zhCN("写当前颜色到选择的调色板槽")

T_("Default palette")
csCZ("Standardní paleta")
deDE("Vorgabepalette")
frFR("Palette par défaut")
huHU("Alapértelmezett paletta")
itIT("Tavolozza di default")
plPL("Domyślna paleta kolorów")
ruRU("Палитра по умолчанию")
srSP("Podrazumevana paleta")
zhCN("缺省调色板")

T_("Restore default system palette")
csCZ("Nastavit standardní systémovou paletu")
deDE("Voreingestellte Systempalette wiederherstellen")
frFR("Restaurer la palette système par défaut")
huHU("Alapértelmezett rendszer paletta visszaállítása")
itIT("Ripristina la tavolozza di default")
plPL("Przywróc standardową systemową paletę kolorów")
ruRU("Восстановить системную палитру по умолчанию")
srSP("Vrati standardnu paletu sistema")
zhCN("恢复到缺省系统调色板")

T_("Save as..")
csCZ("Uložit jako...")
deDE("Speichern unter ...")
frFR("Enregistrer sous..")
huHU("Mentés másként..")
itIT("Salva come..")
plPL("Zapisz jako...")
ruRU("Сохранить как...")
srSP("Sačuvaj kao..")
zhCN("保存为")

T_("Store palette information into a disk file")
csCZ("Uložit paletu do souboru")
deDE("Paletteninformationen in einer Datei speichern")
frFR("Enregistrer la palette dans un fichier ")
huHU("Palettainformáció tárolása fájlba")
itIT("salva la tavolozza in un file su disco")
plPL("Zapisz informacje o palecie kolorów do pliku")
ruRU("Сохранить информацию о палитре в файл "
     "на диск")
srSP("Sačuvaj paletu u fajl na disku")
zhCN("保存调色板信息到磁盘文件")

T_("Load")
csCZ("Načíst...")
deDE("Laden")
frFR("Charger")
huHU("Betöltés")
itIT("Carica")
plPL("Ładuj")
ruRU("Загрузить")
srSP("Učitaj")
zhCN("装载")

T_("Load previously saved palette")
csCZ("Načíst paletu z dříve uloženého souboru")
deDE("Zuvor gespeicherte Palette laden")
frFR("Charger une palette précédemment sauvée")
huHU("Az előző tárolt paletta betöltése")
itIT("Carica la tavolozza precedentemente salvata")
plPL("Ładuj ostatnio zapisaną paletę kolorów")
ruRU("Загрузить сохранённую палитру")
srSP("Učitaj prethodno sačuvanu paletu")
zhCN("载入以前保存的调色板")

T_("Small")
csCZ("Malá")
deDE("Klein")
frFR("Petit")
huHU("Kicsi")
itIT("Piccolo")
plPL("Mały")
ruRU("Маленький")
srSP("Mali")
zhCN("小")

T_("Set up palette size 4 times 4 colors")
csCZ("Nastavit rozměry palety 4 x 4 polí")
deDE("Palette in der Größe von 4 mal 4 Farben erstellen")
frFR("Modifier la taille de la palette à 4x4")
huHU("Palettaméret 4x4 színre állítása")
itIT("Imposta la tavolozza a 4 colori alla volta")
plPL("Ustaw rozmiar palety 4 na 4 kolory")
ruRU("Установить размер палитры 16 цветов")
srSP("Podesi veličinu palete na 4x4 boje")
zhCN("设置调色板大小为4倍4颜色")

T_("Medium")
csCZ("Střední")
deDE("Mittel")
frFR("Moyen")
huHU("Közepes")
itIT("Medio")
plPL("Średni")
ruRU("Средний")
srSP("Srednji")
zhCN("中")

T_("Set up palette size 8 times 8 colors")
csCZ("Nastavit rozměry palety 8 x 8 polí")
deDE("Palette in der Größe von 8 mal 8 Farben erstellen")
frFR("Modifier la taille de la palette à 8x8")
huHU("Palettaméret 8x8 színre állítása")
itIT("Imposta la tavolozza a 8 colori alla volta")
plPL("Ustaw rozmiar palety 8 na 8 kolorów")
ruRU("Установить размер палитры 64 цветов")
srSP("Podesi veličinu palete na 8x8 boja")
zhCN("设置调色板大小为8倍8颜色")

T_("Large")
csCZ("Velká")
deDE("Groß")
frFR("Large")
huHU("Nagy")
itIT("Largo")
plPL("Duży")
ruRU("Большой")
srSP("Velika")
zhCN("大")

T_("Set up palette size 16 times 16 colors (maximum size)")
csCZ("Nastavit rozměry palety 16 x 16 polí (max. velikost)")
deDE("Palette in der Größe von 16 mal 16 Farben erstellen (Maximalgröße)")
frFR("Modifier la taille de la palette à 16x16")
huHU("Palettaméret 16x16 színre állítása")
itIT("Imposta la tavolozza a 16 colori alla volta (dimensione massima)")
plPL("Ustaw rozmiar palety 16 na 16 kolorów")
ruRU("Установить размер палитры 256 цветов (максимальный "
     "размер)")
srSP("Podesi veličinu palete na 16x16 boja (maksimalna veličina)")
zhCN("设置调色板大小为16倍16颜色(最大)")

T_("Custom...")
csCZ("Vlastní...")
deDE("Eigen ...")
frFR("Personnalisé...")
huHU("Választott...")
itIT("Personalizzato...")
plPL("Własny...")
ruRU("Пользовательская...")
srSP("Proizvoljno...")
zhCN("定制...")

T_("Select custom palette size")
csCZ("Zvolit vlastní počet polí v paletě")
deDE("Eigene Palettengröße auswählen")
frFR("Sélectionner une taille personnalisée de palette")
huHU("Választott palettaméret beállítása")
itIT("Seleziona tavolozza di dimensione personalizzata")
plPL("Ustaw własny rozmiar palety kolorów")
ruRU("Выберите размер пользовательской палитры")
srSP("Izaberi proizvoljnu veličinu palete")
zhCN("选择定制调色板大小")

T_("Palette (*.pal)")
csCZ("Paleta (*.pal)")
deDE("Palette (*.pal)")
frFR("Palette (*.pal)")
huHU("Paletta (*.pal)")
itIT("Tavolozza (*.pal)")
plPL("Paleta (*.pal)")
ruRU("Палитра (*.pal)")
srSP("Paleta (*.pal)")
zhCN("调色板(*.pal)")

T_("*.pal")
csCZ("*.pal")
deDE("*.pal")
frFR("*.pal")
huHU("*.pal")
itIT("*.pal")
plPL("*.pal")
ruRU("")
srSP("*.pal")
zhCN("*.pal")

T_("pal")
csCZ("pal")
deDE("pal")
frFR("pal")
huHU("pal")
itIT("pal")
plPL("pal")
ruRU("")
srSP("pal")
zhCN("pal")

T_("Save palette as..")
csCZ("Uložit paletu jako...")
deDE("Palette speichern unter ...")
frFR("Sauver la palette sous..")
huHU("Paletta mentése más néven..")
itIT("Salva tavolozza come..")
plPL("Zapisz paletę kolorów jako...")
ruRU("Сохранить палитру как...")
srSP("Sačuvajte paletu kao...")
zhCN("保存调色板为..")

T_("Error writing file [* \001%s\001].")
csCZ("Chyba při zápisu do souboru [* \001%s\001].")
deDE("Fehler beim Schreiben der Datei [* \001%s\001]")
frFR("Erreur d'écriture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl írásakor")
itIT("Errore di scrittura file [* \001%s\001].")
plPL("Błąd zapisu pliku [* \001%s\001].")
ruRU("Ошибка записи файла [* \001%s\001].")
srSP("Greška prilikom pisanja fajla [* \001%s\001].")
zhCN("写文件错误[* \001%s\001].")

T_("Load palette..")
csCZ("Načíst paletu...")
deDE("Palette laden ...")
frFR("Charger la palette..")
huHU("Paletta betöltése..")
itIT("Carica tavolozza..")
plPL("Ładuj paletę kolorów...")
ruRU("Загрузить палитру...")
srSP("Učitaj paletu..")
zhCN("装载调色板..")

T_("Error opening file [* \001%s\001].")
csCZ("Nelze otevřít soubor [* \001%s\001].")
deDE("Fehler beim Öffnen der Datei [* \001%s\001]")
frFR("Erreur d'ouverture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl megnyitásakor")
itIT("Errore di aprtura file [* \001%s\001].")
plPL("Błąd otwarcia pliku [* \001%s\001].")
ruRU("Ошибка открытия файла [* \001%s\001].")
srSP("Greška prilikom otvaranja fajla [* \001%s\001].")
zhCN("打开文件错误[* \001%s\001].")

T_("Error reading palette from file [* \001%s\001].")
csCZ("Chyba při načítání palety ze souboru [* \001%s\001].")
deDE("Fehler beim Lesen der Palette aus der Datei [* \001%s\001]")
frFR("Erreur de lecture du fichier de palette [* \001%s\001].")
huHU("Hiba a paletta beolvasásakor a [* \001%s\001] fájlból")
itIT("Errore di lettura tavolozza dal file [* \001%s\001].")
plPL("Błąd czytania palety kolorów z pliku [* \001%s\001].")
ruRU("Ошибка чтения палитры из файла [* \001%s\001].")
srSP("Greška prilikom čitanja fajla [* \001%s\001].")
zhCN("从文件[* \001%s\001]. 读调色板错")

T_("Palette dimensions")
csCZ("Rozměry palety")
deDE("Palettenmaße")
frFR("Dimensions de la palette")
huHU("Paletta dimenziói")
itIT("Dimensioni tavolozza")
plPL("Rozmiary palety kolorów")
ruRU("Размер палитры")
srSP("Dimenzije palete")
zhCN("调色板维度")

T_("(transparent)")
csCZ("(průhledná)")
deDE("(transparent)")
frFR("transparent")
huHU("(átlátszó)")
itIT("(trasparente)")
plPL("(przezroczysty)")
ruRU("(прозрачный)")
srSP("(transparenta)")
zhCN("(透明)")

T_("Palette")
csCZ("Paleta")
deDE("Palette")
frFR("Palette")
huHU("Paletta")
itIT("Tavolozza")
plPL("Paleta")
ruRU("Палитра")
srSP("Paleta")
zhCN("调色板")

T_("Wheel")
csCZ("Kolo")
deDE("Farbkreis")
frFR("Molette")
huHU("Korong")
itIT("Ruota")
plPL("Koło")
ruRU("Колесо")
srSP("Točak")
zhCN("滚轮")

T_("Hue")
csCZ("Odstín")
deDE("Farbton")
frFR("Tinte")
huHU("Színezet")
itIT("Tinta")
plPL("Odcień")
ruRU("Оттенок")
srSP("Obojenost")
zhCN("色调")

T_("RGB")
csCZ("RGB")
deDE("RGB")
frFR("RVB")
huHU("RGB")
itIT("RGB")
plPL("RGB")
ruRU("")
srSP("RGB")
zhCN("RGB")

T_("HSV")
csCZ("HSV")
deDE("FSH")
frFR("HSV")
huHU("HSB")
itIT("HSV")
plPL("HSV")
ruRU("")
srSP("HSV")
zhCN("HSV")

T_("Select color")
csCZ("Výběr barvy")
deDE("Farbe auswählen")
frFR("Sélectionner la couleur")
huHU("Szín választása")
itIT("Seleziona colore")
plPL("Wybrany kolor")
ruRU("Выбирите цвет")
srSP("Izaberi boju")
zhCN("选择颜色")


// FileSel.cpp

T_("[A3* Unable to read the directory !]&&")
csCZ("[A3* Nelze načíst obsah adresáře !]&&")
deDE("[A3* Verzeichnis kann nicht gelesen werden!]&&")
frFR("[A3* Impossible de lire le répertoire !]&&")
huHU("[A3* Nem sikerült olvasni a mappát!]&&")
itIT("[A3* Impossibile leggere la cartella !]&&")
plPL("[A3* Nie można odczytać katalogu !]&&")
ruRU("[A3* Не могу прочитать папку!]&&")
srSP("[A3* Ne mogu da pročitam folder!]&&")
zhCN("[A3* 不能读取目录 !]&&")

T_(" is directory.")
csCZ(" je adresář.")
deDE(" ist ein Verzeichnis.")
frFR(" est un répertoire.")
huHU("mappa")
itIT(" è una cartella.")
plPL(" jest katalogiem.")
ruRU(" папка.")
srSP(" je folder.")
zhCN(" 为目录.")

T_(" already exists.&Do you want to continue ?")
csCZ(" již existuje.&Přejete si pokračovat ?")
deDE(" existiert bereits. &Möchten Sie fortfahren?")
frFR(" existe déjà.&Voulez-vous continuer ?")
huHU("már létezik. &Folytatás?")
itIT(" esiste già.&Desideri proseguire ?")
plPL(" już istnieje. &Czy chcesz kontynuować ?")
ruRU(" уже существует. &Вы хотите продолжить?")
srSP(" već postoji. &Da li želite da nastavite?")
zhCN(" 已经存在.继续(&D)?")

T_(" does not exist.")
csCZ(" neexistuje.")
deDE(" existiert nicht.")
frFR(" n'existe pas.")
huHU("nem létezik")
itIT(" non esistono.")
plPL(" nie istnieje.")
ruRU(" не существует.")
srSP(" ne postoji.")
zhCN("不存在")

T_("&do not exist.")
csCZ("&neexistují.")
deDE("")
frFR("&n'existe pas")
huHU("&nem létezik")
itIT(" non esiste")
plPL(" &nie istnieje.")
ruRU("&не существует.")
srSP("&ne postoji.")
zhCN("不存在(&d)")

T_("&Do you want to continue ?")
csCZ("&Přejete si pokračovat ?")
deDE("&Möchten Sie fortfahren?")
frFR("&Voulez-vous continuer ?")
huHU("&Folytatás?")
itIT("&Desideri proseguire ?")
plPL("&Czy chcesz kontynuować ?")
ruRU("&Вы хотите продолжить?")
srSP("&Da li želite da nastavite?")
zhCN("继续(&D)?")

T_("Custom file type (")
csCZ("Jiný typ souboru (")
deDE("Eigener Dateityp (")
frFR("Type de fichier personnalisé (")
huHU("Választott fájltípus (")
itIT("Tipo file personalizzato (")
plPL("Własny typ pliku (")
ruRU("Свой тип файла (")
srSP("Proizvoljni tip fajla (")
zhCN("定制文件类型 (")

T_("New directory")
csCZ("Nový adresář")
deDE("Neues Verzeichnis")
frFR("Nouveau répertoire")
huHU("Új mappa")
itIT("Nuova cartella")
plPL("Nowy katalog")
ruRU("Новая папка")
srSP("Novi folder")
zhCN("新建文件夹")

T_("Name")
csCZ("Jméno")
deDE("Name")
frFR("Nom")
huHU("Név")
itIT("Nome")
plPL("Nazwa")
ruRU("Имя")
srSP("Ime")
zhCN("名称")

T_("[A3* Creating directory failed !&&]")
csCZ("[A3* Chyba při vytváření adresáře !&&]")
deDE("[A3* Verzeichnis konnte nicht erstellt werden!&&]")
frFR("[A3* La création du répertoire a échoué !&&]")
huHU("[A3* A mappa létrehozása sikertelen!&&]")
itIT("[A3* Creazione cartella fallita !&&]")
plPL("[A3* Tworzenie katalogu nie powiodło się !&&]")
ruRU("[A3* Не удалось создать папку!&&]")
srSP("[A3* Pravljenje foldera nije uspelo!&&]")
zhCN("[A3* 创建文件夹失败 !&&]")

T_("Mask")
csCZ("Maska")
deDE("Maske")
frFR("Masque")
huHU("Maszk")
itIT("Maschera")
plPL("Maska")
ruRU("Маска")
srSP("Maska")
zhCN("掩码")

T_("Add to selection")
csCZ("Přidat k výběru")
deDE("Zur Auswahl hinzufügen")
frFR("Ajouter à la sélection")
huHU("Hozzáadás a kijelöléshez")
itIT("Aggiungi alla selezione")
plPL("Dodaj do zaznaczonych")
ruRU("Добавить к выделению")
srSP("Dodaj u izbor")
zhCN("选上")

T_("Remove from selection")
csCZ("Odebrat od výběru")
deDE("Aus der Auswahl entfernen")
frFR("Enlever de la sélection")
huHU("Eltávolítás a kijelölésből")
itIT("Rimuovi dalla selezione")
plPL("Usuń z zaznaczonych")
ruRU("Убрать из выделения")
srSP("Ukloni iz selekcije")
zhCN("去选")

T_("  Drive")
csCZ("  Disková jednotka")
deDE("  Laufwerk")
frFR("  Disque")
huHU("Meghajtó")
itIT(" Disco")
plPL("  Napęd")
ruRU("  Диск")
srSP(" Disk")
zhCN("  驱动")

T_("Directory  ")
csCZ("Adresář  ")
deDE("Verzeichnis  ")
frFR("Répertoire")
huHU("Mappa")
itIT("Cartella ")
plPL("Katalog  ")
ruRU("Папка  ")
srSP("Folder ")
zhCN("文件夹  ")

T_("Open")
csCZ("Otevřít")
deDE("Öffnen")
frFR("Ouvrir")
huHU("Megnyitás")
itIT("Apri")
plPL("Otwórz")
ruRU("Открыть")
srSP("Otvori")
zhCN("打开")

T_("Save")
csCZ("Uložit")
deDE("Speichern")
frFR("Sauver")
huHU("Mentés")
itIT("Salva")
plPL("Zapisz")
ruRU("Сохранить")
srSP("Sačuvaj")
zhCN("保存")

T_("[A3* Renaming of file failed !&&]")
csCZ("[A3* Chyba při přejmenovávání souboru !&&]")
deDE("[A3* Datei konnte nicht umbenannt werden!&&]")
frFR("[A3* Le renommage du fichier a échoué !&&]")
huHU("[A3* A fájl átnevezése sikertelen!&&]")
itIT("[A3* Rinomina fallito !&&]")
plPL("[A3* Zmiana nazwy pliku nie powiodła się !&&]")
ruRU("[A3* Не удалось переименовать файл!&&]")
srSP("[A3* Promena imena fajla nije uspela!&&]")
zhCN("[A3* 文件重命名失败 !&&]")

T_("All files")
csCZ("Všechny soubory")
deDE("Alle Dateien")
frFR("Tous les fichiers")
huHU("Az összes fájl")
itIT("Titti i files")
plPL("Wszystkie pliki")
ruRU("Все файлы")
srSP("Svi fajlovi")
zhCN("所有文件")

T_("&Select")
csCZ("&Vybrat")
deDE("&Auswählen")
frFR("&Sélectionner")
huHU("&Kijelölés")
itIT("Seleziona")
plPL("&Wybierz")
ruRU("&Выбрать")
srSP("&Izaberi")
zhCN("选择(&S)")

T_("Save as")
csCZ("Uložit jako")
deDE("Speichern unter")
frFR("Sauver sous")
huHU("Mentés más néven")
itIT("Salva come")
plPL("Zapisz jako")
ruRU("Сохранить как")
srSP("Sačuvaj kao")
zhCN("另存为")

T_("Select directory")
csCZ("Vybrat adresář")
deDE("Verzeichnis auswählen")
frFR("Sélectionner un répertoire")
huHU("Mappa kijelölése")
itIT("Seleziona cartella")
plPL("Wybierz katalog")
ruRU("Выберите папку")
srSP("Izaberi folder")
zhCN("选择文件夹")

T_("Dir up")
csCZ("Nadřazený adresář")
deDE("Übergeordnetes Vwerzeichnis")
frFR("Répertoire parent")
huHU("Szülőmappa")
itIT("Cartella su")
plPL("Katalog w górę")
ruRU("Папка вверх")
srSP("Folder iznad")
zhCN("向上")

T_("Create directory")
csCZ("Vytvořit adresář")
deDE("Verzeichnis erstellen")
frFR("Créer un répertoire")
huHU("Mappa létrehozása")
itIT("Crea nuova cartella")
plPL("Utwórz katalog")
ruRU("Создать папку")
srSP("Napravi folder")
zhCN("创建文件夹")

T_("Select files")
csCZ("Označit soubory")
deDE("Dateien auswählen")
frFR("Sélectionner les fichiers")
huHU("Fájlok kijelölése")
itIT("Seleziona i files")
plPL("Wybierz pliki")
ruRU("Выделить файлы")
srSP("Izaberite fajlove")
zhCN("选择文件")

T_("Unselect files")
csCZ("Odznačit soubory")
deDE("Dateien abwählen")
frFR("Désélectionner les fichiers")
huHU("Fájlkijelölés megszüntetése")
itIT("Deseleziona i files")
plPL("Odznacz pliki")
ruRU("Убрать выделение файлов")
srSP("Deselektujte fajlove")
zhCN("取消选择文件")

T_("Toggle files")
csCZ("Inverze označení")
deDE("Dateiauswahl umkehren")
frFR("Invertir la sélection")
huHU("Kijelölés felcserélése")
itIT("Inverti selezione")
plPL("Odwróć zaznaczone pliki")
ruRU("Поменять выделение файлов")
srSP("Invertuj izabrane")
zhCN("Toggle files")


// Windows.cpp

T_("Activate window")
csCZ("Aktivovat okno")
deDE("Fenster aktivieren")
frFR("Activer la fenêtre")
huHU("Ablak aktiválása")
itIT("Attiva finestra")
plPL("Aktywuj okno")
ruRU("Активное окно")
srSP("Aktviraj prozor")
zhCN("激活窗口")

T_("Activate this window")
csCZ("Aktivovat toto okno")
deDE("Dieses Fenster aktivieren")
frFR("Activer cette fenêtre")
huHU("Ez az ablak aktív")
itIT("Attiva questa finestra")
plPL("Aktywuj to okno")
ruRU("Сделать активным это окно")
srSP("Aktiviraj ovaj prozor")
zhCN("激活当前窗口")

T_("More windows..")
csCZ("Další okna..")
deDE("Weitere Fenster ...")
frFR("Plus de fenêtres..")
huHU("Több ablak..")
itIT("Altre finestre")
plPL("Więcej okien..")
ruRU("Ещё окна...")
srSP("Još prozora..")
zhCN("更多窗口")


// Win32.cpp

T_("Open..")
csCZ("Otevřít..")
deDE("Öffnen ...")
frFR("Ouvrir..")
huHU("Megnyitás..")
itIT("Apri..")
plPL("Otwórz..")
ruRU("Открыть...")
srSP("Otvori..")
zhCN("打开..")


// CtrlUtil.cpp

T_("Invalid data.")
csCZ("Chybný údaj.")
deDE("Ungültige Daten")
frFR("Donnée invalide.")
huHU("Érvénytelen adat")
itIT("Dato non valido.")
plPL("Niepoprawna data.")
ruRU("Неверные данные.")
srSP("Nevalidni podaci.")
zhCN("无效数据")


// Update.cpp

T_("Updating ")
csCZ("Aktualizuji ")
deDE("Updaten von ")
frFR("Mise à jour de ")
huHU("Frissítés ")
itIT("Aggiornamento")
plPL("Aktualizacja ")
ruRU("Обновление ")
srSP("Ažuriram ")
zhCN("更新中 ")

T_("Error creating file [* \001%s\001].")
csCZ("Nelze vytvořit soubor [* \001%s\001].")
deDE("Fehler beim Erstellen der Datei [* \001%s\001]")
frFR("Erreur en créant le fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl létrehozásánál")
itIT("Errore creazione file [* \001%s\001].")
plPL("Błąd tworzenia pliku [* \001%s\001].")
ruRU("Ошибка создания файла [* \001%s\001].")
srSP("Greška pri pravljenju fajla [* \001%s\001].")
zhCN("创建文件错误 [* \001%s\001].")

T_("Aborting update is likely to cause trouble when running the application "
     "for the next time.\nContinue?")
csCZ("Přerušení aktualizace může vést k velkým problémům při příštím "
     "spuštění aplikace.\nPokračovat?")
deDE("Abbruch des Updates wird wahrscheinlich beim nächsten Start der Anwendung "
     "Probleme hervorrufen.\nFortfahren?")
frFR("Interrompre une mise à jour peut causer de sérieux problèmes lors du "
     "prochain démarrage de l'application.\nContinuer ?")
huHU("A frissítés megszakítása problémákat okozhataz alkalmazás futtatásánál.\n"
     "Folytatás?")
itIT("Interrompere l'aggiornamento può causare seri problemi al prossimo avvio.\n"
     "Continuare?")
plPL("Przerwanie aktualizacji najprawdopodobniej spowoduje kłopoty przy ponownym "
     "uruchomieniu aplikacji.\nKontynuować?")
ruRU("Отмена обновления может повести за собой "
     "проблемы при запуске приложения в следующий "
     "раз.\nПродолжить?")
srSP("Prekid ažuriranja će verovatno prouzrokovati nevolje kada startujete "
     "aplikaciju sledeći put.\nNastaviti?")
zhCN("放弃可能导致下次运行本程序出现问题.\n继续?")


// Ctrl.lay

T_("Test")
csCZ("Test")
deDE("Test")
frFR("Tester")
huHU("Próba")
itIT("Test")
plPL("Test")
ruRU("Тест")
srSP("Test")
zhCN("测试")

T_("&Directory")
csCZ("&Adresář")
deDE("&Verzeichnis")
frFR("&Répertoire")
huHU("&Mappa")
itIT("&Cartella")
plPL("&Katalog")
ruRU("&Папка")
srSP("&Folder")
zhCN("文件夹(&D)")

T_("&File")
csCZ("&Soubor")
deDE("&Datei")
frFR("&Fichier")
huHU("&Fájl")
itIT("&File")
plPL("&Plik")
ruRU("&Файл")
srSP("&Fajl")
zhCN("文件(&F)")

T_("&Type")
csCZ("&Typ")
deDE("&Typ")
frFR("&Type")
huHU("&Típus")
itIT("&Tipo")
plPL("&Typ")
ruRU("&Тип")
srSP("&Tip")
zhCN("类型(&T)")

T_("&Sort by")
csCZ("&Třídit dle")
deDE("&Sortiert nach")
frFR("&Trier par")
huHU("&Rendezés")
itIT("&Ordina per")
plPL("&Sortuj w/g")
ruRU("&Cортировать по")
srSP("&Sortiraj po")
zhCN("排序(&S)于")

T_("Name\nExtension")
csCZ("Jména\nPřípony")
deDE("Name\nErweiterung")
frFR("Nom\nExtension")
huHU("Név\nKiterjesztés")
itIT("Nome\nEstensione")
plPL("Nazwy\nRozszerzenia")
ruRU("Имя\nРасширение")
srSP("Ime\nEkstenzija")
zhCN("名称\n扩展")

T_("Read only")
csCZ("Jen číst")
deDE("Schreibgeschützt")
frFR("Lecture seule")
huHU("Csak olvasható")
itIT("Sola lettura")
plPL("Tylko do odczytu")
ruRU("Только для чтения")
srSP("Samo za čitanje")
zhCN("只读")

T_("Color:")
csCZ("B&arva:")
deDE("Farbe:")
frFR("Couleur :")
huHU("Szín:")
itIT("Colore")
plPL("Kolor:")
ruRU("Цвет:")
srSP("Boja:")
zhCN("颜色")

T_("R:")
csCZ("&R:")
deDE("R:")
frFR("R :")
huHU("R:")
itIT("R:")
plPL("R:")
ruRU("")
srSP("R:")
zhCN("R:")

T_("G:")
csCZ("&G:")
deDE("G:")
frFR("V :")
huHU("G:")
itIT("G:")
plPL("G:")
ruRU("")
srSP("G:")
zhCN("G:")

T_("B:")
csCZ("&B:")
deDE("B:")
frFR("B :")
huHU("B:")
itIT("B:")
plPL("B:")
ruRU("")
srSP("B:")
zhCN("B:")

T_("H:")
csCZ("&H:")
deDE("F:")
frFR("H :")
huHU("H:")
itIT("h:")
plPL("H:")
ruRU("")
srSP("H:")
zhCN("H:")

T_("S:")
csCZ("&S:")
deDE("S:")
frFR("S :")
huHU("S:")
itIT("S:")
plPL("S:")
ruRU("")
srSP("S:")
zhCN("S:")

T_("V:")
csCZ("&V:")
deDE("H:")
frFR("V :")
huHU("V:")
itIT("V:")
plPL("V:")
ruRU("")
srSP("V:")
zhCN("V:")

T_("&Rows:")
csCZ("Řa&dy:")
deDE("&Zeilen:")
frFR("&Lignes :")
huHU("&Sorok:")
itIT("&Righe")
plPL("&Wiersze:")
ruRU("&Ряды:")
srSP("&Redovi:")
zhCN("行(&R)")

T_("&Columns:")
csCZ("&Sloupce:")
deDE("&Spalten:")
frFR("&Colonnes :")
huHU("&Oszlopok:")
itIT("&Colonne")
plPL("&Kolumny:")
ruRU("&Колонки:")
srSP("&Kolone:")
zhCN("列(&C)")

T_("Default")
csCZ("Základní")
deDE("Voreinstellung")
frFR("Par défaut")
huHU("Alapértelmezett")
itIT("Predefiniti")
plPL("Domyślny")
ruRU("По умолчанию")
srSP("Podrazumevano")
zhCN("缺省")

T_("Printer")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Drukarka")
ruRU("")
srSP("")
zhCN("打印机")

T_("Paper size")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Rozmiar strony")
ruRU("")
srSP("")
zhCN("纸张大小")

T_("Input slot")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Slot wejściowy")
ruRU("")
srSP("")
zhCN("输入槽")

T_("Pages per sheet")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Stron na arkusz")
ruRU("")
srSP("")
zhCN("每sheet页数")

T_("Print range")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Zakres drukowania")
ruRU("")
srSP("")
zhCN("打印范围")

T_("All pages\nCurrent page\nPages from")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Wszystkie strony\nBieżąca strona\nStrony od")
ruRU("")
srSP("")
zhCN("所有页\n当前页\n始于页")

T_("to")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("do")
ruRU("")
srSP("")
zhCN("到")

T_("Copies")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Kopie")
ruRU("")
srSP("")
zhCN("份数")

T_("Collate")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Zestaw")
ruRU("")
srSP("")
zhCN("比较")

T_("Portrait\nLandscape")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Portret\nKrajobraz")
ruRU("")
srSP("")
zhCN("纵向\n横向")

T_("Placement")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
plPL("Umiejscowienie")
ruRU("")
srSP("")
zhCN("布局")


// Obsolete

T_("1 / 1")
csCZ("1 / 1")
deDE("1 / 1")
frFR("1 / 1")
huHU("1 / 1")
itIT("1 / 1")
plPL("1 / 1")
ruRU("")
srSP("1 / 1")
zhCN("1 / 1")

T_("Sideways")
csCZ("Na šířku")
deDE("Querformat")
frFR("Direction")
huHU("Oldalsáv")
itIT("Direzione")
plPL("Z boku")
ruRU("По бокам")
srSP("Sa strane")
zhCN("侧边")

T_("&1 page\n&2 pages\n&4 pages\n&8 pages")
csCZ("&1 strana\n&2 strany\n&4 strany\n&8 stran")
deDE("&1 Seite\n&2 Seiten\n&4 Seiten\n&8 Seiten")
frFR("&1 page\n&2 pages\n&4 pages\n&8 pages")
huHU("&1 oldal\n&2 oldal\n&4 oldal\n&8 oldal")
itIT("&1 pagina\n&2 pagine\n&4 pagine\n&8 pagine")
plPL("&1 strona\n&2 strony\n&4 strony\n&8 stron")
ruRU("&1 страница\n&2 страницы\n&4 страницы\n&8 страниц")
srSP("&1 strana\n&2 strane\n&4 strane\n&8 strana")
zhCN("&1 页\n&2 页\n&4 页\n&8 页")

T_("Page &numbers")
csCZ("Čísla &stránek")
deDE("&Seitenzahlen")
frFR("&Numéros de page")
huHU("&Oldalszámok")
itIT("&Numero pagine")
plPL("Numery &stron")
ruRU("&Номера страниц")
srSP("&Broj strana")
zhCN("页码(&n)")

T_("PDF export..")
csCZ("PDF export..")
deDE("PDF-Export ...")
frFR("Export PDF..")
huHU("")
itIT("")
plPL("Eksport do PDF...")
ruRU("")
srSP("PDF eksport..")
zhCN("输出PDF..")

T_("Report")
csCZ("Výstupní sestava")
deDE("Bericht")
frFR("Rapport")
huHU("Jelentés")
itIT("Report")
plPL("&Raport")
ruRU("Отчёт")
srSP("Izveštaj")
zhCN("报告")

T_("&Print")
csCZ("&Tisk")
deDE("&Drucken")
frFR("&Imprimer")
huHU("&Nyomtatás")
itIT("&Stampa")
plPL("&Drukuj")
ruRU("&Печать")
srSP("&Štampa")
zhCN("打印(&P)")
