
// EditCtrl.h

T_("(default)")
csCZ("(výchozí)")
deDE("(Voreinstellung)")
frFR("")
huHU("")
itIT("(predefinito)")
ruRU("")
srSP("")


// EditField.cpp

T_("Undo")
csCZ("Zpět")
deDE("Rückgängig")
frFR("Annuler")
huHU("Visszavonás")
itIT("Annulla")
ruRU("Отменить")
srSP("Undo")

T_("Cut")
csCZ("Vyjmout")
deDE("Ausschneiden")
frFR("Couper")
huHU("Kivágás")
itIT("Taglia")
ruRU("Вырезать")
srSP("Iseci")

T_("Copy")
csCZ("Kopírovat")
deDE("Kopieren")
frFR("Copier")
huHU("Másolás")
itIT("Copia")
ruRU("Копировать")
srSP("Kopiraj")

T_("Paste")
csCZ("Vložit")
deDE("Einfügen")
frFR("Coller")
huHU("Beillesztés")
itIT("Incolla")
ruRU("Вставить")
srSP("Zalepi")

T_("Erase")
csCZ("Vymazat")
deDE("Löschen")
frFR("Effacer")
huHU("Törlés")
itIT("Cancella")
ruRU("Стереть")
srSP("Obriši")

T_("Select all")
csCZ("Vybrat vše")
deDE("Alles auswählen")
frFR("Tout sélectionner")
huHU("Minden kiválasztása")
itIT("Seleziona tutto")
ruRU("Выделить всё")
srSP("Izaberi sve")


// Text.cpp

T_("Redo")
csCZ("Znovu")
deDE("Wiederherstellen")
frFR("Refaire")
huHU("Újra végrehajtás")
itIT("Ripeti")
ruRU("Повторить")
srSP("Redo")


// ArrayCtrl.cpp

T_("Do you really want to delete the selected %s ?")
csCZ("Smazat aktuální %s ?")
deDE("Möchten Sie die ausgewählte %s wirklich löschen?")
frFR("Voulez-vous réellement supprimer le %s sélectioné ?")
huHU("Biztosan töröljük a kijelölt %s ?")
itIT("Vuoi realmente cancellare la %s selezionata ?")
ruRU("Вы действительно хотите удалить выделенный "
     "%s?")
srSP("Da li stvarno želite da obrišete izabran %s?")

T_("Insert %s")
csCZ("Vložit %s")
deDE("%s einfügen")
frFR("Insérer %s")
huHU("Beszúrás")
itIT("Inserisci %s")
ruRU("Вставить %s")
srSP("Ubaci %s")

T_("Insert a new %s into the table.")
csCZ("Vložit do tabulky nový %s.")
deDE("Neue %s in die Tabelle einfügen")
frFR("Insère une nouvelle %d dans la table.")
huHU("Új %s beszúrása a táblázatba")
itIT("Inserisce una nuova %s nella tabella.")
ruRU("Вставить новый %s в таблицу.")
srSP("Ubaci u tabelu novi %s.")

T_("Insert %s before")
csCZ("Vložit %s před")
deDE("%s vorher einfügen")
frFR("Insérer %s avant")
huHU("%s beszúrása elé")
itIT("Inserisci %s sopra")
ruRU("Вставить %s перед")
srSP("Ubaci %s pre")

T_("Insert a new %s into the table before the actual one")
csCZ("Vložit nový %s před aktuální")
deDE("Neue %s vor der aktuellen in die Tabelle einfügen")
frFR("Insérer une nouvelle %d dans la table avant l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
itIT("Inserisce una nuova %s prima di quella selezioanta")
ruRU("Вставить новый %s в таблицу перед существующим")
srSP("Ubaci novi %s u tabeli pre trenutne")

T_("Insert %s after")
csCZ("Vložit %s za")
deDE("%s danach einfügen")
frFR("Insérer %s après")
huHU("% beszúrása mögé")
itIT("Inserisci %s sotto")
ruRU("Вставить %s после")
srSP("Ubaci %s posle")

T_("Insert a new %s into the table after the actual one")
csCZ("Vložit %s za aktuální")
deDE("Neue %s hinter der aktuellen in die Tabelle einfügen")
frFR("Insérer une nouvelle %d dans la table après l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
itIT("Inserisce una nuova %s dopo quella selezioanta")
ruRU("Вставить новый %s в таблицу после существующего")
srSP("Ubaci novi %s u tabeli posle trenutne")

T_("Append %s")
csCZ("Přidat %s")
deDE("%s hinzufügen")
frFR("Ajouter %s")
huHU("%s hozzáfűzése")
itIT("Aggiungi %s")
ruRU("Добавить %s")
srSP("Dodaj %s")

T_("Append a new %s at the end of the table.")
csCZ("Přidat nový %s na konec")
deDE("Neue %s am Ende der Tabelle hinzufügen")
frFR("Ajouter une nouvelle %s à la fin de la table.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
itIT("Aggiunge una nuova %s al fondo della tabella.")
ruRU("Добавить новый %s в конце таблицы.")
srSP("Dodaj novi %s na kraju tabele.")

T_("Duplicate %s")
csCZ("Duplikovat %s")
deDE("%s duplizieren")
frFR("Dupliquer %s")
huHU("%s megkettőzése")
itIT("Duplica %s")
ruRU("Дублировать %s")
srSP("Dupliraj %s")

T_("Duplicate current table %s.")
csCZ("Vložit do tabulky duplikát aktuálního %s.")
deDE("Aktuelle %s der Tabelle duplizieren")
frFR("Dupliquer la table %s sélectionnée.")
huHU("Az aktuális táblázat megkettőzése")
itIT("Duplica la tabella %s selezionata.")
ruRU("Дублировать текущий %s таблицы.")
srSP("Dupliraj trenutni %s tabele.")

T_("Edit %s")
csCZ("Opravit aktuální %s")
deDE("%s bearbeiten")
frFR("Editer %s")
huHU("%s szerkesztése")
itIT("Edita %s")
ruRU("Редактировать %s")
srSP("Promeni %s")

T_("Edit active %s.")
csCZ("Opravit aktuální %s.")
deDE("Aktive %s bearbeiten")
frFR("Editer %s actif.")
huHU("Az aktuális %s szerkesztése")
itIT("Edita la %s attiva.")
ruRU("Редактировать активный %s.")
srSP("Promeni aktivni %s.")

T_("Delete %s\tDelete")
csCZ("Odstranit %s\tDelete")
deDE("%s löschen\tLöschen")
frFR("Supprimer %s\tSupprimer")
huHU("Törlés %s\tTörlés")
itIT("Cancella %s\tCancella")
ruRU("Удалить %s\tУдалить")
srSP("Obriši %s\tObriši")

T_("Delete active %s.")
csCZ("Odstranit aktuální %s.")
deDE("Aktive %s löschen")
frFR("Supprimer %s actif.")
huHU("Az aktív %s törlése")
itIT("Cancella %s attiva.")
ruRU("Удалить активный %s.")
srSP("Obriši aktivni %s.")

T_("Move %s up")
csCZ("Posunout %s nahoru")
deDE("%s nach oben verschieben")
frFR("Monter %s")
huHU("%s felfelé mozgatása")
itIT("Sposta %s su")
ruRU("Двигать %s вверх")
srSP("Pomeri %s na gore")

T_("Swap %s with previous thus moving it up.")
csCZ("Vyměnit aktuální %s s předchozím a tak ho posunout nahoru.")
deDE("%s mit der vorigen vertauschen und so nach oben verschieben")
frFR("Intervertir %s avec le précédent.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
itIT("Inverte la %s con la precedente.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")
srSP("Zameni %s sa prethodnim, pomeri ga na gore.")

T_("Move %s down")
csCZ("Posunout %s dolů")
deDE("%s nach unten verschieben")
frFR("Descendre %s")
huHU("%s lefelé mozgatása")
itIT("Sposta %s giu")
ruRU("Двигать %s вниз")
srSP("Pomeri %s dole")

T_("Swap %s with next thus moving it down.")
csCZ("Vyměnit aktuální %s s dalším a tak ho posunout dolů.")
deDE("%s mit der nächsten vertauschen und so nach unten verschieben")
frFR("Intervertir %s avec le suivant.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
itIT("Inverte la %s la successiva.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")
srSP("Zameni %s sa sledećim, pomeri ga na dole.")

T_("Select all table rows")
csCZ("Vybrat všechny řádky v tabulce")
deDE("Alle Zeilen der Tabelle auswählen")
frFR("Sélectionner toutes les lignes")
huHU("Az összes sor kijelölése")
itIT("Seleziona tutte le righe")
ruRU("Выделить все ряды таблицы")
srSP("Izaberi sve redove tabele")

T_("row")
csCZ("řádek")
deDE("Zeile")
frFR("ligne")
huHU("sor")
itIT("riga")
ruRU("ряды")
srSP("red")


// Progress.cpp

T_("Working...")
csCZ("Pracuji...")
deDE("Bearbeitung läuft ...")
frFR("En cours d'exécution...")
huHU("Folyamatban...")
itIT("Esecuzione...")
ruRU("Обработка...")
srSP("Radim...")


// AKeys.cpp

T_("Setup keys")
csCZ("Nastavit klávesy")
deDE("Tasten zuweisen")
frFR("Configurer les raccourcis")
huHU("Billentyűk beállítása")
itIT("Selezione tasti veloci")
ruRU("")
srSP("Podesi tastere")

T_("Group")
csCZ("Skupina")
deDE("Gruppe")
frFR("Groupe")
huHU("Csoport")
itIT("Gruppo")
ruRU("")
srSP("Grupa")

T_("Action")
csCZ("Akce")
deDE("Aktion")
frFR("Action")
huHU("Művelet")
itIT("Azione")
ruRU("")
srSP("Akcija")

T_("Key 1")
csCZ("Klávesa 1")
deDE("Taste 1")
frFR("Touche 1")
huHU("1. billentyű")
itIT("Combinazione 1")
ruRU("")
srSP("Taster 1")

T_("Key 2")
csCZ("Klávesa 2")
deDE("Taste 2")
frFR("Touche 2")
huHU("2. billentyű")
itIT("Combinazione 2")
ruRU("")
srSP("Taster 2")


// Prompt.cpp

T_("OK")
csCZ("OK")
deDE("OK")
frFR("Ok")
huHU("Rendben")
itIT("Ok")
ruRU("OK")
srSP("OK")

T_("Cancel")
csCZ("Storno")
deDE("Abbrechen")
frFR("Annuler")
huHU("Mégsem")
itIT("Annulla")
ruRU("Отмена")
srSP("Otkaži")

T_("&Yes")
csCZ("&Ano")
deDE("&Ja")
frFR("&Oui")
huHU("&Igen")
itIT("&Si")
ruRU("&Да")
srSP("&Da")

T_("&No")
csCZ("&Ne")
deDE("&Nein")
frFR("&Non")
huHU("&Nem")
itIT("&No")
ruRU("&Нет")
srSP("&Ne")

T_("&Abort")
csCZ("&Přerušit")
deDE("&Abbrechen")
frFR("&Interrompre")
huHU("&Megszakítás")
itIT("&Interrompi")
ruRU("&Прервать")
srSP("&Prekini")

T_("&Retry")
csCZ("&Opakovat")
deDE("&Erneut versuchen")
frFR("&Réessayer")
huHU("&Újra")
itIT("&Riprova")
ruRU("П&овторить")
srSP("&Ponovi")

T_("&Cancel")
csCZ("&Zrušit")
deDE("&Abbrechen")
frFR("&Annuler")
huHU("Mégsem")
itIT("&Annulla")
ruRU("&Отменить")
srSP("&Otkaži")


// Help.cpp

T_("Go Back")
csCZ("Předchozí téma")
deDE("Rückwärts")
frFR("Précédent")
huHU("Visszalépés")
itIT("Indiatro")
ruRU("Назад")
srSP("Nazad")

T_("Go Forward")
csCZ("Další téma")
deDE("Vorwärts")
frFR("Suivant")
huHU("Előrelépés")
itIT("Avanti")
ruRU("Вперёд")
srSP("Napred")

T_("Font size")
csCZ("Velikost")
deDE("Schriftgrad")
frFR("Taille de police")
huHU("Betűméret")
itIT("Dimensione font")
ruRU("Размер шрифта")
srSP("Veličina fonta")

T_("Print")
csCZ("Tisk")
deDE("Drucken")
frFR("Imprimer")
huHU("Nyomtatás")
itIT("Stampa")
ruRU("Печать")
srSP("Štampa")

T_("Help")
csCZ("Nápověda")
deDE("Hilfe")
frFR("Aide")
huHU("Súgó")
itIT("Aiuto")
ruRU("Помощь")
srSP("Pomoć")


// StatusBar.cpp

T_("Ready")
csCZ("Připraven")
deDE("Fertig")
frFR("Prêt")
huHU("Kész")
itIT("Pronto")
ruRU("Готов")
srSP("Spreman")


// TabCtrl.cpp

T_("Apply")
csCZ("Použít")
deDE("Übernehmen")
frFR("Appliquer")
huHU("")
itIT("Applica")
ruRU("")
srSP("Primeni")

T_("Close")
csCZ("Zavřít")
deDE("Schließen")
frFR("Fermer")
huHU("")
itIT("Chiudi")
ruRU("")
srSP("Zatvori")


// DlgColor.cpp

T_("(no color)")
csCZ("(bez barvy)")
deDE("(keine Farbe)")
frFR("(aucune couleur)")
huHU("(nincs szín)")
itIT("(nessun colore)")
ruRU("нет цвета")
srSP("(bez boje)")

T_("Set color")
csCZ("Nastavit barvu")
deDE("Farbe festlegen")
frFR("Appliquer la couleur")
huHU("Szín beállítása")
itIT("(Set colore)")
ruRU("Установить цвет")
srSP("Postavi boju")

T_("Write current color to selected palette slot")
csCZ("Nastavit barvu pole v paletě na aktuální kreslicí barvu")
deDE("Palettenplatz mit aktueller Farbe belegen")
frFR("Ecrire la couleur courante dans l'emplacement sélectionné de la palette")
huHU("Aktuális szín beírása a kijelölt palettamezőbe")
itIT("Salva il colore corrente nello slot selezionato della tavolozza")
ruRU("Записать текущий цвет в выделенный слот "
     "палитры")
srSP("Zapiši trenutnu boju u izabranu paletu boja")

T_("Default palette")
csCZ("Standardní paleta")
deDE("Vorgabepalette")
frFR("Palette par défaut")
huHU("Alapértelmezett paletta")
itIT("Tavolozza di default")
ruRU("Палитра по умолчанию")
srSP("Podrazumevana paleta")

T_("Restore default system palette")
csCZ("Nastavit standardní systémovou paletu")
deDE("Voreingestellte Systempalette wiederherstellen")
frFR("Restaurer la palette système par défaut")
huHU("Alapértelmezett rendszer paletta visszaállítása")
itIT("Ripristina la tavolozza di default")
ruRU("Восстановить системную палитру по умолчанию")
srSP("Vrati standardnu paletu sistema")

T_("Save as..")
csCZ("Uložit jako...")
deDE("Speichern unter ...")
frFR("Enregistrer sous..")
huHU("Mentés másként..")
itIT("Salva come..")
ruRU("Сохранить как...")
srSP("Sačuvaj kao..")

T_("Store palette information into a disk file")
csCZ("Uložit paletu do souboru")
deDE("Paletteninformationen in einer Datei speichern")
frFR("Enregistrer la palette dans un fichier ")
huHU("Palettainformáció tárolása fájlba")
itIT("salva la tavolozza in un file su disco")
ruRU("Сохранить информацию о палитре в файл "
     "на диск")
srSP("Sačuvaj paletu u fajl na disku")

T_("Load")
csCZ("Načíst...")
deDE("Laden")
frFR("Charger")
huHU("Betöltés")
itIT("Carica")
ruRU("Загрузить")
srSP("Učitaj")

T_("Load previously saved palette")
csCZ("Načíst paletu z dříve uloženého souboru")
deDE("Zuvor gespeicherte Palette laden")
frFR("Charger une palette précédemment sauvée")
huHU("Az előző tárolt paletta betöltése")
itIT("Carica la tavolozza precedentemente salvata")
ruRU("Загрузить сохранённую палитру")
srSP("Učitaj prethodno sačuvanu paletu")

T_("Small")
csCZ("Malá")
deDE("Klein")
frFR("Petit")
huHU("Kicsi")
itIT("Piccolo")
ruRU("Маленький")
srSP("Mali")

T_("Set up palette size 4 times 4 colors")
csCZ("Nastavit rozměry palety 4 x 4 polí")
deDE("Palette in der Größe von 4 mal 4 Farben erstellen")
frFR("Modifier la taille de la palette à 4x4")
huHU("Palettaméret 4x4 színre állítása")
itIT("Imposta la tavolozza a 4 colori alla volta")
ruRU("Установить размер палитры 16 цветов")
srSP("Podesi veličinu palete na 4x4 boje")

T_("Medium")
csCZ("Střední")
deDE("Mittel")
frFR("Moyen")
huHU("Közepes")
itIT("Medio")
ruRU("Средний")
srSP("Srednji")

T_("Set up palette size 8 times 8 colors")
csCZ("Nastavit rozměry palety 8 x 8 polí")
deDE("Palette in der Größe von 8 mal 8 Farben erstellen")
frFR("Modifier la taille de la palette à 8x8")
huHU("Palettaméret 8x8 színre állítása")
itIT("Imposta la tavolozza a 8 colori alla volta")
ruRU("Установить размер палитры 64 цветов")
srSP("Podesi veličinu palete na 8x8 boja")

T_("Large")
csCZ("Velká")
deDE("Groß")
frFR("Large")
huHU("Nagy")
itIT("Largo")
ruRU("Большой")
srSP("Velika")

T_("Set up palette size 16 times 16 colors (maximum size)")
csCZ("Nastavit rozměry palety 16 x 16 polí (max. velikost)")
deDE("Palette in der Größe von 16 mal 16 Farben erstellen (Maximalgröße)")
frFR("Modifier la taille de la palette à 16x16")
huHU("Palettaméret 16x16 színre állítása")
itIT("Imposta la tavolozza a 16 colori alla volta (dimensione massima)")
ruRU("Установить размер палитры 256 цветов (максимальный "
     "размер)")
srSP("Podesi veličinu palete na 16x16 boja (maksimalna veličina)")

T_("Custom...")
csCZ("Vlastní...")
deDE("Eigen ...")
frFR("Personnalisé...")
huHU("Választott...")
itIT("Personalizzato...")
ruRU("Пользовательская...")
srSP("Proizvoljno...")

T_("Select custom palette size")
csCZ("Zvolit vlastní počet polí v paletě")
deDE("Eigene Palettengröße auswählen")
frFR("Sélectionner une taille personnalisée de palette")
huHU("Választott palettaméret beállítása")
itIT("Seleziona tavolozza di dimensione personalizzata")
ruRU("Выберите размер пользовательской палитры")
srSP("Izaberi proizvoljnu veličinu palete")

T_("Palette (*.pal)")
csCZ("Paleta (*.pal)")
deDE("Palette (*.pal)")
frFR("Palette (*.pal)")
huHU("Paletta (*.pal)")
itIT("Tavolozza (*.pal)")
ruRU("Палитра (*.pal)")
srSP("Paleta (*.pal)")

T_("*.pal")
csCZ("*.pal")
deDE("*.pal")
frFR("*.pal")
huHU("*.pal")
itIT("*.pal")
ruRU("")
srSP("*.pal")

T_("pal")
csCZ("pal")
deDE("pal")
frFR("pal")
huHU("pal")
itIT("pal")
ruRU("")
srSP("pal")

T_("Save palette as..")
csCZ("Uložit paletu jako...")
deDE("Palette speichern unter ...")
frFR("Sauver la palette sous..")
huHU("Paletta mentése más néven..")
itIT("Salva tavolozza come..")
ruRU("Сохранить палитру как...")
srSP("Sačuvajte paletu kao...")

T_("Error writing file [* \001%s\001].")
csCZ("Chyba při zápisu do souboru [* \001%s\001].")
deDE("Fehler beim Schreiben der Datei [* \001%s\001]")
frFR("Erreur d'écriture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl írásakor")
itIT("Errore di scrittura file [* \001%s\001].")
ruRU("Ошибка записи файла [* \001%s\001].")
srSP("Greška prilikom pisanja fajla [* \001%s\001].")

T_("Load palette..")
csCZ("Načíst paletu...")
deDE("Palette laden ...")
frFR("Charger la palette..")
huHU("Paletta betöltése..")
itIT("Carica tavolozza..")
ruRU("Загрузить палитру...")
srSP("Učitaj paletu..")

T_("Error opening file [* \001%s\001].")
csCZ("Nelze otevřít soubor [* \001%s\001].")
deDE("Fehler beim Öffnen der Datei [* \001%s\001]")
frFR("Erreur d'ouverture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl megnyitásakor")
itIT("Errore di aprtura file [* \001%s\001].")
ruRU("Ошибка открытия файла [* \001%s\001].")
srSP("Greška prilikom otvaranja fajla [* \001%s\001].")

T_("Error reading palette from file [* \001%s\001].")
csCZ("Chyba při načítání palety ze souboru [* \001%s\001].")
deDE("Fehler beim Lesen der Palette aus der Datei [* \001%s\001]")
frFR("Erreur de lecture du fichier de palette [* \001%s\001].")
huHU("Hiba a paletta beolvasásakor a [* \001%s\001] fájlból")
itIT("Errore di lettura tavolozza dal file [* \001%s\001].")
ruRU("Ошибка чтения палитры из файла [* \001%s\001].")
srSP("Greška prilikom čitanja fajla [* \001%s\001].")

T_("Palette dimensions")
csCZ("Rozměry palety")
deDE("Palettenmaße")
frFR("Dimensions de la palette")
huHU("Paletta dimenziói")
itIT("Dimensioni tavolozza")
ruRU("Размер палитры")
srSP("Dimenzije palete")

T_("(transparent)")
csCZ("(průhledná)")
deDE("(transparent)")
frFR("transparent")
huHU("(átlátszó)")
itIT("(trasparente)")
ruRU("(прозрачный)")
srSP("(transparenta)")

T_("Palette")
csCZ("Paleta")
deDE("Palette")
frFR("Palette")
huHU("Paletta")
itIT("Tavolozza")
ruRU("Палитра")
srSP("Paleta")

T_("Wheel")
csCZ("Kolo")
deDE("Farbkreis")
frFR("Molette")
huHU("Korong")
itIT("Ruota")
ruRU("Колесо")
srSP("Točak")

T_("Hue")
csCZ("Odstín")
deDE("Farbton")
frFR("Tinte")
huHU("Színezet")
itIT("Tinta")
ruRU("Оттенок")
srSP("Obojenost")

T_("RGB")
csCZ("RGB")
deDE("RGB")
frFR("RVB")
huHU("RGB")
itIT("RGB")
ruRU("")
srSP("RGB")

T_("HSV")
csCZ("HSV")
deDE("FSH")
frFR("HSV")
huHU("HSB")
itIT("HSV")
ruRU("")
srSP("HSV")

T_("Select color")
csCZ("Výběr barvy")
deDE("Farbe auswählen")
frFR("Sélectionner la couleur")
huHU("Szín választása")
itIT("Seleziona colore")
ruRU("Выбирите цвет")
srSP("Izaberi boju")


// FileSel.cpp

T_("[A3* Unable to read the directory !]&&")
csCZ("[A3* Nelze načíst obsah adresáře !]&&")
deDE("[A3* Verzeichnis kann nicht gelesen werden!]&&")
frFR("[A3* Impossible de lire le répertoire !]&&")
huHU("[A3* Nem sikerült olvasni a mappát!]&&")
itIT("[A3* Impossibile leggere la cartella !]&&")
ruRU("[A3* Не могу прочитать папку!]&&")
srSP("[A3* Ne mogu da pročitam folder!]&&")

T_(" is directory.")
csCZ(" je adresář.")
deDE(" ist ein Verzeichnis.")
frFR(" est un répertoire.")
huHU("mappa")
itIT(" è una cartella.")
ruRU(" папка.")
srSP(" je folder.")

T_(" already exists.&Do you want to continue ?")
csCZ(" již existuje.&Přejete si pokračovat ?")
deDE(" existiert bereits. &Möchten Sie fortfahren?")
frFR(" existe déjà.&Voulez-vous continuer ?")
huHU("már létezik. &Folytatás?")
itIT(" esiste già.&Desideri proseguire ?")
ruRU(" уже существует. &Вы хотите продолжить?")
srSP(" već postoji. &Da li želite da nastavite?")

T_(" does not exist.")
csCZ(" neexistuje.")
deDE(" existiert nicht.")
frFR(" n'existe pas.")
huHU("nem létezik")
itIT(" non esistono.")
ruRU(" не существует.")
srSP(" ne postoji.")

T_("&do not exist.")
csCZ("&neexistují.")
deDE("")
frFR("&n'existe pas")
huHU("&nem létezik")
itIT(" non esiste")
ruRU("&не существует.")
srSP("&ne postoji.")

T_("&Do you want to continue ?")
csCZ("&Přejete si pokračovat ?")
deDE("&Möchten Sie fortfahren?")
frFR("&Voulez-vous continuer ?")
huHU("&Folytatás?")
itIT("&Desideri proseguire ?")
ruRU("&Вы хотите продолжить?")
srSP("&Da li želite da nastavite?")

T_("Custom file type (")
csCZ("Jiný typ souboru (")
deDE("Eigener Dateityp (")
frFR("Type de fichier personnalisé (")
huHU("Választott fájltípus (")
itIT("Tipo file personalizzato (")
ruRU("Свой тип файла (")
srSP("Proizvoljni tip fajla (")

T_("New directory")
csCZ("Nový adresář")
deDE("Neues Verzeichnis")
frFR("Nouveau répertoire")
huHU("Új mappa")
itIT("Nuova cartella")
ruRU("Новая папка")
srSP("Novi folder")

T_("Name")
csCZ("Jméno")
deDE("Name")
frFR("Nom")
huHU("Név")
itIT("Nome")
ruRU("Имя")
srSP("Ime")

T_("[A3* Creating directory failed !&&]")
csCZ("[A3* Chyba při vytváření adresáře !&&]")
deDE("[A3* Verzeichnis konnte nicht erstellt werden!&&]")
frFR("[A3* La création du répertoire a échoué !&&]")
huHU("[A3* A mappa létrehozása sikertelen!&&]")
itIT("[A3* Creazione cartella fallita !&&]")
ruRU("[A3* Не удалось создать папку!&&]")
srSP("[A3* Pravljenje foldera nije uspelo!&&]")

T_("Mask")
csCZ("Maska")
deDE("Maske")
frFR("Masque")
huHU("Maszk")
itIT("Maschera")
ruRU("Маска")
srSP("Maska")

T_("Add to selection")
csCZ("Přidat k výběru")
deDE("Zur Auswahl hinzufügen")
frFR("Ajouter à la sélection")
huHU("Hozzáadás a kijelöléshez")
itIT("Aggiungi alla selezione")
ruRU("Добавить к выделению")
srSP("Dodaj u izbor")

T_("Remove from selection")
csCZ("Odebrat od výběru")
deDE("Aus der Auswahl entfernen")
frFR("Enlever de la sélection")
huHU("Eltávolítás a kijelölésből")
itIT("Rimuovi dalla selezione")
ruRU("Убрать из выделения")
srSP("Ukloni iz selekcije")

T_("  Drive")
csCZ("  Disková jednotka")
deDE("  Laufwerk")
frFR("  Disque")
huHU("Meghajtó")
itIT(" Disco")
ruRU("  Диск")
srSP(" Disk")

T_("Directory  ")
csCZ("Adresář  ")
deDE("Verzeichnis  ")
frFR("Répertoire")
huHU("Mappa")
itIT("Cartella ")
ruRU("Папка  ")
srSP("Folder ")

T_("Open")
csCZ("Otevřít")
deDE("Öffnen")
frFR("Ouvrir")
huHU("Megnyitás")
itIT("Apri")
ruRU("Открыть")
srSP("Otvori")

T_("Save")
csCZ("Uložit")
deDE("Speichern")
frFR("Sauver")
huHU("Mentés")
itIT("Salva")
ruRU("Сохранить")
srSP("Sačuvaj")

T_("[A3* Renaming of file failed !&&]")
csCZ("[A3* Chyba při přejmenovávání souboru !&&]")
deDE("[A3* Datei konnte nicht umbenannt werden!&&]")
frFR("[A3* Le renommage du fichier a échoué !&&]")
huHU("[A3* A fájl átnevezése sikertelen!&&]")
itIT("[A3* Rinomina fallito !&&]")
ruRU("[A3* Не удалось переименовать файл!&&]")
srSP("[A3* Promena imena fajla nije uspela!&&]")

T_("All files")
csCZ("Všechny soubory")
deDE("Alle Dateien")
frFR("Tous les fichiers")
huHU("Az összes fájl")
itIT("Titti i files")
ruRU("Все файлы")
srSP("Svi fajlovi")

T_("&Select")
csCZ("&Vybrat")
deDE("&Auswählen")
frFR("&Sélectionner")
huHU("&Kijelölés")
itIT("Seleziona")
ruRU("&Выбрать")
srSP("&Izaberi")

T_("Save as")
csCZ("Uložit jako")
deDE("Speichern unter")
frFR("Sauver sous")
huHU("Mentés más néven")
itIT("Salva come")
ruRU("Сохранить как")
srSP("Sačuvaj kao")

T_("Select directory")
csCZ("Vybrat adresář")
deDE("Verzeichnis auswählen")
frFR("Sélectionner un répertoire")
huHU("Mappa kijelölése")
itIT("Seleziona cartella")
ruRU("Выберите папку")
srSP("Izaberi folder")

T_("Dir up")
csCZ("Nadřazený adresář")
deDE("Übergeordnetes Vwerzeichnis")
frFR("Répertoire parent")
huHU("Szülőmappa")
itIT("Cartella su")
ruRU("Папка вверх")
srSP("Folder iznad")

T_("Create directory")
csCZ("Vytvořit adresář")
deDE("Verzeichnis erstellen")
frFR("Créer un répertoire")
huHU("Mappa létrehozása")
itIT("Crea nuova cartella")
ruRU("Создать папку")
srSP("Napravi folder")

T_("Select files")
csCZ("Označit soubory")
deDE("Dateien auswählen")
frFR("Sélectionner les fichiers")
huHU("Fájlok kijelölése")
itIT("Seleziona i files")
ruRU("Выделить файлы")
srSP("Izaberite fajlove")

T_("Unselect files")
csCZ("Odznačit soubory")
deDE("Dateien abwählen")
frFR("Désélectionner les fichiers")
huHU("Fájlkijelölés megszüntetése")
itIT("Deseleziona i files")
ruRU("Убрать выделение файлов")
srSP("Deselektujte fajlove")

T_("Toggle files")
csCZ("Inverze označení")
deDE("Dateiauswahl umkehren")
frFR("Invertir la sélection")
huHU("Kijelölés felcserélése")
itIT("Inverti selezione")
ruRU("Поменять выделение файлов")
srSP("Invertuj izabrane")


// Windows.cpp

T_("Activate window")
csCZ("Aktivovat okno")
deDE("Fenster aktivieren")
frFR("Activer la fenêtre")
huHU("Ablak aktiválása")
itIT("Attiva finestra")
ruRU("Активное окно")
srSP("Aktviraj prozor")

T_("Activate this window")
csCZ("Aktivovat toto okno")
deDE("Dieses Fenster aktivieren")
frFR("Activer cette fenêtre")
huHU("Ez az ablak aktív")
itIT("Attiva questa finestra")
ruRU("Сделать активным это окно")
srSP("Aktiviraj ovaj prozor")

T_("More windows..")
csCZ("Další okna..")
deDE("Weitere Fenster ...")
frFR("Plus de fenêtres..")
huHU("Több ablak..")
itIT("Altre finestre")
ruRU("Ещё окна...")
srSP("Još prozora..")


// Win32.cpp

T_("Open..")
csCZ("Otevřít..")
deDE("Öffnen ...")
frFR("Ouvrir..")
huHU("Megnyitás..")
itIT("Apri..")
ruRU("Открыть...")
srSP("Otvori..")


// CtrlUtil.cpp

T_("Invalid data.")
csCZ("Chybný údaj.")
deDE("Ungültige Daten")
frFR("Donnée invalide.")
huHU("Érvénytelen adat")
itIT("Dato non valido.")
ruRU("Неверные данные.")
srSP("Nevalidni podaci.")


// Update.cpp

T_("Updating ")
csCZ("Aktualizuji ")
deDE("Updaten von ")
frFR("Mise à jour de ")
huHU("Frissítés ")
itIT("Aggiornamento")
ruRU("Обновление ")
srSP("Ažuriram ")

T_("Error creating file [* \001%s\001].")
csCZ("Nelze vytvořit soubor [* \001%s\001].")
deDE("Fehler beim Erstellen der Datei [* \001%s\001]")
frFR("Erreur en créant le fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl létrehozásánál")
itIT("Errore creazione file [* \001%s\001].")
ruRU("Ошибка создания файла [* \001%s\001].")
srSP("Greška pri pravljenju fajla [* \001%s\001].")

T_("Aborting update is likely to cause trouble when running the application "
     "for the next time.\nContinue?")
csCZ("Přerušení aktualizace může vést k velkým problémům při příštím "
     "spuštění aplikace.\nPokračovat?")
deDE("Abbruch des Updates wird wahrscheinlich beim nächsten Start der Anwendung "
     "Probleme hervorrufen.\nFortfahren?")
frFR("Interrompre une mise à jour peut causer de sérieux problèmes lors du "
     "prochain démarrage de l'application.\nContinuer ?")
huHU("A frissítés megszakítása problémákat okozhataz alkalmazás futtatásánál.\n"
     "Folytatás?")
itIT("Interrompere l'aggiornamento può causare seri problemi al prossimo avvio.\n"
     "Continuare?")
ruRU("Отмена обновления может повести за собой "
     "проблемы при запуске приложения в следующий "
     "раз.\nПродолжить?")
srSP("Prekid ažuriranja će verovatno prouzrokovati nevolje kada startujete "
     "aplikaciju sledeći put.\nNastaviti?")


// Ctrl.lay

T_("Test")
csCZ("Test")
deDE("Test")
frFR("Tester")
huHU("Próba")
itIT("Test")
ruRU("Тест")
srSP("Test")

T_("&Directory")
csCZ("&Adresář")
deDE("&Verzeichnis")
frFR("&Répertoire")
huHU("&Mappa")
itIT("&Cartella")
ruRU("&Папка")
srSP("&Folder")

T_("&File")
csCZ("&Soubor")
deDE("&Datei")
frFR("&Fichier")
huHU("&Fájl")
itIT("&File")
ruRU("&Файл")
srSP("&Fajl")

T_("&Type")
csCZ("&Typ")
deDE("&Typ")
frFR("&Type")
huHU("&Típus")
itIT("&Tipo")
ruRU("&Тип")
srSP("&Tip")

T_("&Sort by")
csCZ("&Třídit dle")
deDE("&Sortiert nach")
frFR("&Trier par")
huHU("&Rendezés")
itIT("&Ordina per")
ruRU("&Cортировать по")
srSP("&Sortiraj po")

T_("Name\nExtension")
csCZ("Jména\nPřípony")
deDE("Name\nErweiterung")
frFR("Nom\nExtension")
huHU("Név\nKiterjesztés")
itIT("Nome\nEstensione")
ruRU("Имя\nРасширение")
srSP("Ime\nEkstenzija")

T_("Read only")
csCZ("Jen číst")
deDE("Schreibgeschützt")
frFR("Lecture seule")
huHU("Csak olvasható")
itIT("Sola lettura")
ruRU("Только для чтения")
srSP("Samo za čitanje")

T_("Color:")
csCZ("B&arva:")
deDE("Farbe:")
frFR("Couleur :")
huHU("Szín:")
itIT("Colore")
ruRU("Цвет:")
srSP("Boja:")

T_("R:")
csCZ("&R:")
deDE("R:")
frFR("R :")
huHU("R:")
itIT("R:")
ruRU("")
srSP("R:")

T_("G:")
csCZ("&G:")
deDE("G:")
frFR("V :")
huHU("G:")
itIT("G:")
ruRU("")
srSP("G:")

T_("B:")
csCZ("&B:")
deDE("B:")
frFR("B :")
huHU("B:")
itIT("B:")
ruRU("")
srSP("B:")

T_("H:")
csCZ("&H:")
deDE("F:")
frFR("H :")
huHU("H:")
itIT("h:")
ruRU("")
srSP("H:")

T_("S:")
csCZ("&S:")
deDE("S:")
frFR("S :")
huHU("S:")
itIT("S:")
ruRU("")
srSP("S:")

T_("V:")
csCZ("&V:")
deDE("H:")
frFR("V :")
huHU("V:")
itIT("V:")
ruRU("")
srSP("V:")

T_("&Rows:")
csCZ("Řa&dy:")
deDE("&Zeilen:")
frFR("&Lignes :")
huHU("&Sorok:")
itIT("&Righe")
ruRU("&Ряды:")
srSP("&Redovi:")

T_("&Columns:")
csCZ("&Sloupce:")
deDE("&Spalten:")
frFR("&Colonnes :")
huHU("&Oszlopok:")
itIT("&Colonne")
ruRU("&Колонки:")
srSP("&Kolone:")

T_("Default")
csCZ("Základní")
deDE("Voreinstellung")
frFR("Par défaut")
huHU("Alapértelmezett")
itIT("Predefiniti")
ruRU("По умолчанию")
srSP("Podrazumevano")

T_("Printer")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Paper size")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Input slot")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Pages per sheet")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Print range")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("All pages\nCurrent page\nPages from")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("to")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Copies")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Collate")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Portrait\nLandscape")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")

T_("Placement")
csCZ("")
deDE("")
frFR("")
huHU("")
itIT("")
ruRU("")
srSP("")


// Obsolete

T_("1 / 1")
csCZ("1 / 1")
deDE("1 / 1")
frFR("1 / 1")
huHU("1 / 1")
itIT("1 / 1")
ruRU("")
srSP("1 / 1")

T_("Sideways")
csCZ("Na šířku")
deDE("Querformat")
frFR("Direction")
huHU("Oldalsáv")
itIT("Direzione")
ruRU("По бокам")
srSP("Sa strane")

T_("&1 page\n&2 pages\n&4 pages\n&8 pages")
csCZ("&1 strana\n&2 strany\n&4 strany\n&8 stran")
deDE("&1 Seite\n&2 Seiten\n&4 Seiten\n&8 Seiten")
frFR("&1 page\n&2 pages\n&4 pages\n&8 pages")
huHU("&1 oldal\n&2 oldal\n&4 oldal\n&8 oldal")
itIT("&1 pagina\n&2 pagine\n&4 pagine\n&8 pagine")
ruRU("&1 страница\n&2 страницы\n&4 страницы\n&8 страниц")
srSP("&1 strana\n&2 strane\n&4 strane\n&8 strana")

T_("Page &numbers")
csCZ("Čísla &stránek")
deDE("&Seitenzahlen")
frFR("&Numéros de page")
huHU("&Oldalszámok")
itIT("&Numero pagine")
ruRU("&Номера страниц")
srSP("&Broj strana")

T_("PDF export..")
csCZ("PDF export..")
deDE("PDF-Export ...")
frFR("Export PDF..")
huHU("")
itIT("")
ruRU("")
srSP("PDF eksport..")

T_("Report")
csCZ("Výstupní sestava")
deDE("Bericht")
frFR("Rapport")
huHU("Jelentés")
itIT("Report")
ruRU("Отчёт")
srSP("Izveštaj")

T_("&Print")
csCZ("&Tisk")
deDE("&Drucken")
frFR("&Imprimer")
huHU("&Nyomtatás")
itIT("&Stampa")
ruRU("&Печать")
srSP("&Štampa")
