#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// httpsrv.cpp

T_("If you're not redirected automatically please use %s.")
csCZ("Pokud nebudete automaticky přesměrováni, použijte prosím %s.")
deDE("Wenn Sie nicht automatisch weitergeleitet werden, benutzen Sie bitte %s")
frFR("Si vous n'êtes pas automatiquement redirigé, veuillez utiliser %s.")
huHU("Ha nem történik automatikus átirányítás használja %s")
itIT("")
plPL("Jeśli nie zostałeś automatycznie przekierowany użyj proszę %s.")
ruRU("Если Вы не перенаправлены автоматически, "
     "пожайлуста, используйте %s.")
srSP("")
zhCN("如果没有自动重定向,请使用%s.")

T_("this link")
csCZ("tento odkaz")
deDE(" diesen Link.")
frFR("ce lien")
huHU("ezt a hivatkozást")
itIT("")
plPL("tego odnośnika")
ruRU("эту ссылку")
srSP("")
zhCN("本链接")

T_("Redirection to another web address")
csCZ("Přesměrování na jinou adresu")
deDE("Weiterleitung zu einer anderen Netzadresse")
frFR("Redirection vers une autre adresse web")
huHU("Átirányítás másik webcímre")
itIT("")
plPL("Przekierowanie do innej strony")
ruRU("Перенаправление на другой веб адрес")
srSP("")
zhCN("重定向到其他web地址")

T_("... (total length: %d bytes)")
csCZ("... (celková délka: %d bytů)")
deDE("... (Gesamtgröße: %d Bytes)")
frFR("(longueur totale : %d octets")
huHU("... (teljes hossz: %d bájt)")
itIT("")
plPL("... (całkowita długość: %d bajtów)")
ruRU("... (полный размер: %d байт)")
srSP("")
zhCN("... (总长: %d 字节)")

T_("The web server is unable to satisfy your request:\n<p>\n")
csCZ("Internetový server nebyl schopen vyřídit požadavek:\n<p>\n")
deDE("Der Netzserver kann Ihre Anforderung nicht erfüllen:\n<p>\n")
frFR("Ce serveur web ne peut pas satisfaire votre requête :\n<p>\n")
huHU("A webkiszolgáló nem tudja teljesíteni a kérést:\n<p>\n")
itIT("")
plPL("Ten serwer sieciowy nie jest w stanie odpowiedzieć na twoje żądanie:\n"
     "<p>\n")
ruRU("Этот веб сервер не может удовлетворить "
     "Ваш запрос:\n<p>\n")
srSP("")
zhCN("web服务器不支持您的请求:\n<p>\n")

T_("Reason:")
csCZ("Důvod chyby: ")
deDE("Grund:")
frFR("Raison :")
huHU("Ok:")
itIT("")
plPL("Powód:")
ruRU("Причина:")
srSP("")
zhCN("原因:")

T_("Detailed query data:")
csCZ("Detailní informace o dotazu:")
deDE("Genaue Abfragedaten:")
frFR("Données détaillées de la requête :")
huHU("Részletes lekérési adatok:")
itIT("")
plPL("Szczegółowe dane zapytania:")
ruRU("Детали запроса:")
srSP("")
zhCN("详细查询数据")

T_("Web server error")
csCZ("Chyba internetového serveru")
deDE("Netzserverfehler")
frFR("Erreur du serveur web")
huHU("Webkiszolgáló hiba")
itIT("")
plPL("Błąd serwera sieciowego")
ruRU("Ошибка веб сервера")
srSP("")
zhCN("Web服务器错误")


// httpcli.cpp

T_("%s:%d receiving headers timed out")
csCZ("%s:%d vypršel časový limit při načítání hlaviček")
deDE("%s:%d Timeout beim Headerempfang")
frFR("%s:%d temps dépassé à la réception de l'en-tête")
huHU("")
itIT("")
plPL("%s:%d przekroczono czas odbierania nagłówka")
ruRU("")
srSP("")
zhCN("%s:%d 接收头超时")

T_("%s:%d: connecting to host timed out")
csCZ("%s:%d: vypršel časový limit pro připojení k hostiteli")
deDE("%s:%d Timeout bei der Verbindungsaufnahme mit dem Server")
frFR("%s:%d : l'hôte n'a pas accepté la connexion dans le temps imparti")
huHU("")
itIT("")
plPL("%s:%d przekroczono czas łączenia się z hostem")
ruRU("")
srSP("")
zhCN("%s:%d: 连接到主机超时")

T_("%s:%d: timed out sending request to server")
csCZ("%s:%d: vypršel časový limit při odesílání požadavku")
deDE("%s:%d Timeout beim Übermitteln der Abfrage an den Server")
frFR("%s:%d : le serveur n'a pas répondu dans le temps imparti")
huHU("%s:%d: időtúllépés a kérés elküldésénél")
itIT("")
plPL("%s:%d: przekroczono czas wysyłania żądania do serwera")
ruRU("%s:%d: таймаут отправки запроса на сервер")
srSP("")
zhCN("%s:%d: 发送请求到服务器超时")

T_("%s:%d: invalid server response: %s")
csCZ("%s:%d: neplatná odezva ze serveru: %s")
deDE("%s:%d: Ungültige Serverantwort: %s")
frFR("%s:%d : réponse du serveur invalide : %s")
huHU("%s:%d: érvénytelen kiszolgálói válasz")
itIT("")
plPL("%s:%d: niepoprawna odpowiedź serwera: %s")
ruRU("%s:%d: неправильный ответ сервера: %s")
srSP("")
zhCN("%s:%d: 无效服务器反应: %s")

T_("%s:%d: maximum data length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka dat (%d B)")
deDE("%s:%d: Maximale Datenlänge überschritten (%d B)")
frFR("%s:%d : dépassement de la longueur maximale des données (%d O)")
huHU("%s:%d: maximális adathossz túllépése (%d B)")
itIT("")
plPL("%s:%d: przekroczono dopuszczalny rozmiar danych (%d B)")
ruRU("%s:%d: превышен максимальный размер данных "
     "(%d B)")
srSP("")
zhCN("%s:%d: 超出了最大数据长度(%d B)")

T_("%s:%d: maximum header length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka hlaviček (%d B)")
deDE("%s:%d: Maximale Headerlänge überschritten (%d B)")
frFR("%s:%d : dépassement de la longueur maximale de l'en-tête (%d O)")
huHU("%s:%d: maximális fejléchossz túllépése (%d B)")
itIT("")
plPL("%s:%d: przekroczono dopuszczalną długość nagłówka (%d B)")
ruRU("%s:%d: превышен максимальный размер заголовка "
     "(%d B)")
srSP("")
zhCN("%s:%d: 超出了最大头长度(%d B)")

T_("%s:%d: timed out when receiving server response")
csCZ("%s:%d: vypršel časový limit při načítání odpovědi")
deDE("%s:%d: Timeout beim Empfang der Serverantwort")
frFR("%s%d : temps dépassé à la réception de la réponse du serveur")
huHU("%s:%d: időtúllépés a kiszolgáló válaszára várva")
itIT("")
plPL("%s:%d: przekroczono czas oczekiwania na odpowiedź serwera")
ruRU("%s:%d: таймаут при приёме ответа от сервера")
srSP("")
zhCN("%s:%d: 接收服务器反应时超时")

T_("Maximum content size exceeded: %d")
csCZ("Překročena maximální povolená délka datového obsahu: %d")
deDE("Maximaler Datenumfang überschritten: %d")
frFR("")
huHU("A maximális tartalomhossz túllépve: %d")
itIT("")
plPL("Przekroczono dopuszczalny rozmiar zawartości: %d")
ruRU("Превышен максимальный размер содержимого: "
     "%d")
srSP("")
zhCN("最大内容长度超出:%d")

T_("Partial input: %d out of %d")
csCZ("Přijata neúplná data: %d z %d")
deDE("Unvollständiger Empfang: %d von %d")
frFR("Saisie partielle : %d de %d")
huHU("Részleges beolvasás: %d a %d-ból")
itIT("")
plPL("Dane częściowe: %d z %d")
ruRU("Частичный ввод: %d из %d")
srSP("")
zhCN("部分输入: %d out of %d")


// sproc.cpp

T_("pipe() error; error code = %d")
csCZ("chyba pipe(); kód chyby = %d")
deDE("pipe()-Fehler; Fehlercode = %d")
frFR("erreur pipe(); code d'erreur = %d")
huHU("pipe() hiba; hibakód = %d")
itIT("")
plPL("błąd pipe(); kod błędu = %d")
ruRU("ошибка pipe(); код ошибки = %d")
srSP("")
zhCN("pipe() error; error code = %d")

T_("fork() error; error code = %d")
csCZ("chyba fork(); kód chyby = %d")
deDE("fork()-Fehler; Fehlercode = %d")
frFR("erreur fork(); code d'erreur = %d")
huHU("fork() hiba; hibakód = %d")
itIT("")
plPL("błąd fork(); kod błędu = %d")
ruRU("ошибка fork(); код ошибки = %d")
srSP("")
zhCN("fork() error; error code = %d")

T_("Opening host '%s' / port %d failed, error = %s")
csCZ("Připojování k hostiteli '%s' / port %d selhalo, chyba = %s")
deDE("Zugriff auf den Host '%s' / port %d fehlgeschlagen, Fehler = %s")
frFR("Erreur d'ouverture de '%s' / port %d, erreur = %s")
huHU("A '%s' gép / %d port megnyitása sikertelen, hiba = %s")
itIT("")
plPL("Łączenie z hostem '%s' / port %d nie powiodło się, błąd = %s")
ruRU("Подсоединение к хосту '%s' / порту %d не удачно, "
     "ошибка = %s")
srSP("")
zhCN("Opening host '%s' / port %d failed, error = %s")

T_("Error running process: %s\nCommand: %s")
csCZ("Chyba při spouštění procesu: %s\nPříkaz: %s")
deDE("Fehler beim Ausführen des Prozesses: %s\nBefehl: %s")
frFR("Erreur d'exécution du programme : %s\nCommande : %s")
huHU("Hiba a %s folyamat\n%s parancs futtatásánál")
itIT("")
plPL("Błąd uruchamiania procesu: %s\nKomenda: %s")
ruRU("Ошибка при запуске процесса: %s\nКоманда: "
     "%s")
srSP("")
zhCN("运行进城错误:%s\n命令: %s")

T_("Communication error; process = %s")
csCZ("Chyba spojení; proces = %s")
deDE("Kommunikationsfehler; Prozess = %s")
frFR("Erreur de communication ; processus = %s")
huHU("Kommunikációs hiba; folyamat = %s")
itIT("")
plPL("Błąd komunikacji; proces = %s")
ruRU("Ошибка коммуникации; процесс = %s")
srSP("")
zhCN("通信错误; 进城 = %s")

T_("Missing command line (host = %s).")
csCZ("Chybí příkazová řádka (hostitel = %s).")
deDE("Fehlende Befehlszeile (Host = %s)")
frFR("Ligne de commande manquante (hôte = %s).")
huHU("Hiányzó parancssor (gép = %s)")
itIT("")
plPL("Brak linii poleceń (host = %s).")
ruRU("Не указана командная строка (хост = %s)")
srSP("")
zhCN("缺少命令行(主机 = %s).")
