#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// httpsrv.cpp

T_("If you're not redirected automatically please use %s.")
csCZ("Pokud nebudete automaticky přesměrováni, použijte prosím %s.")
deDE("Wenn Sie nicht automatisch weitergeleitet werden, benutzen Sie bitte %s")
fiFI("Jos toiminto ei etene automaattisesti, käytä %s.")
frFR("Si vous n'êtes pas automatiquement redirigé, veuillez utiliser %s.")
huHU("Ha nem történik automatikus átirányítás használja %s")
itIT("")
plPL("Jeśli nie zostałeś automatycznie przekierowany użyj proszę %s.")
ruRU("Если Вы не перенаправлены автоматически, "
     "пожайлуста, используйте %s.")
srSP("")
trTR("Eğer otomatik olarak yönlendirlmediyseniz lütfen %s bağlantısını "
     "kullanın.")
zhCN("如果没有自动重定向,请使用%s.")

T_("this link")
csCZ("tento odkaz")
deDE(" diesen Link.")
fiFI("tämä linkki")
frFR("ce lien")
huHU("ezt a hivatkozást")
itIT("")
plPL("tego odnośnika")
ruRU("эту ссылку")
srSP("")
trTR("bu bağlantı")
zhCN("本链接")

T_("Redirection to another web address")
csCZ("Přesměrování na jinou adresu")
deDE("Weiterleitung zu einer anderen Netzadresse")
fiFI("Reititys toiseen web -osoitteeseen")
frFR("Redirection vers une autre adresse web")
huHU("Átirányítás másik webcímre")
itIT("")
plPL("Przekierowanie do innej strony")
ruRU("Перенаправление на другой веб адрес")
srSP("")
trTR("başka bir ağ adresine yönlendiriliyor")
zhCN("重定向到其他web地址")

T_("... (total length: %d bytes)")
csCZ("... (celková délka: %d bytů)")
deDE("... (Gesamtgröße: %d Bytes)")
fiFI("... (kokonaispituus: %d tavua)")
frFR("(longueur totale : %d octets")
huHU("... (teljes hossz: %d bájt)")
itIT("")
plPL("... (całkowita długość: %d bajtów)")
ruRU("... (полный размер: %d байт)")
srSP("")
trTR("... (toplam boyut: %d byte)")
zhCN("... (总长: %d 字节)")

T_("The web server is unable to satisfy your request:\n<p>\n")
csCZ("Internetový server nebyl schopen vyřídit požadavek:\n<p>\n")
deDE("Der Netzserver kann Ihre Anforderung nicht erfüllen:\n<p>\n")
fiFI("Web palvelin ei kykene täyttämään pyyntöäsi:\n<p>\n")
frFR("Ce serveur web ne peut pas satisfaire votre requête :\n<p>\n")
huHU("A webkiszolgáló nem tudja teljesíteni a kérést:\n<p>\n")
itIT("")
plPL("Ten serwer sieciowy nie jest w stanie odpowiedzieć na twoje żądanie:\n"
     "<p>\n")
ruRU("Этот веб сервер не может удовлетворить "
     "Ваш запрос:\n<p>\n")
srSP("")
trTR("Ağ sunucusu isteğinizi yerine getiremiyor:\n<p>\n")
zhCN("web服务器不支持您的请求:\n<p>\n")

T_("Reason:")
csCZ("Důvod chyby: ")
deDE("Grund:")
fiFI("Syy:")
frFR("Raison :")
huHU("Ok:")
itIT("")
plPL("Powód:")
ruRU("Причина:")
srSP("")
trTR("Sebep:")
zhCN("原因:")

T_("Detailed query data:")
csCZ("Detailní informace o dotazu:")
deDE("Genaue Abfragedaten:")
fiFI("Yksityiskohtainen kysely tieto:")
frFR("Données détaillées de la requête :")
huHU("Részletes lekérési adatok:")
itIT("")
plPL("Szczegółowe dane zapytania:")
ruRU("Детали запроса:")
srSP("")
trTR("Detaylı sorgulama verileri:")
zhCN("详细查询数据")

T_("Web server error")
csCZ("Chyba internetového serveru")
deDE("Netzserverfehler")
fiFI("Web -palvelin virhe")
frFR("Erreur du serveur web")
huHU("Webkiszolgáló hiba")
itIT("")
plPL("Błąd serwera sieciowego")
ruRU("Ошибка веб сервера")
srSP("")
trTR("Sunucu hatası")
zhCN("Web服务器错误")


// httpcli.cpp

T_("%s:%d receiving headers timed out")
csCZ("%s:%d vypršel časový limit při načítání hlaviček")
deDE("%s:%d Timeout beim Headerempfang")
fiFI("%s:%d headerien vastaanotto aikakatkaistu")
frFR("%s:%d temps dépassé à la réception de l'en-tête")
huHU("")
itIT("")
plPL("%s:%d przekroczono czas odbierania nagłówka")
ruRU("")
srSP("")
trTR("%s:%d: Üstbilgi alışverişi zaman aşımına uğradı.")
zhCN("%s:%d 接收头超时")

T_("%s:%d: connecting to host timed out")
csCZ("%s:%d: vypršel časový limit pro připojení k hostiteli")
deDE("%s:%d Timeout bei der Verbindungsaufnahme mit dem Server")
fiFI("%s:%d: kytkeytyminen isäntään aikakatkaistu")
frFR("%s:%d : l'hôte n'a pas accepté la connexion dans le temps imparti")
huHU("")
itIT("")
plPL("%s:%d przekroczono czas łączenia się z hostem")
ruRU("")
srSP("")
trTR("%s:%d: Sunucu bağlantısı zaman aşımına uğradı")
zhCN("%s:%d: 连接到主机超时")

T_("%s:%d: timed out sending request to server")
csCZ("%s:%d: vypršel časový limit při odesílání požadavku")
deDE("%s:%d Timeout beim Übermitteln der Abfrage an den Server")
fiFI("%s:%d: palvelupyynnön lähettäminen palvelimelle aikakatkaistu")
frFR("%s:%d : le serveur n'a pas répondu dans le temps imparti")
huHU("%s:%d: időtúllépés a kérés elküldésénél")
itIT("")
plPL("%s:%d: przekroczono czas wysyłania żądania do serwera")
ruRU("%s:%d: таймаут отправки запроса на сервер")
srSP("")
trTR("%s:%d: İstek zaman aşımına uğradı")
zhCN("%s:%d: 发送请求到服务器超时")

T_("%s:%d: invalid server response: %s")
csCZ("%s:%d: neplatná odezva ze serveru: %s")
deDE("%s:%d: Ungültige Serverantwort: %s")
fiFI("%s:%d: virheellinen palvelinvastine: %s")
frFR("%s:%d : réponse du serveur invalide : %s")
huHU("%s:%d: érvénytelen kiszolgálói válasz")
itIT("")
plPL("%s:%d: niepoprawna odpowiedź serwera: %s")
ruRU("%s:%d: неправильный ответ сервера: %s")
srSP("")
trTR("%s:%d: Sunucudan gelen yanıt geçersiz")
zhCN("%s:%d: 无效服务器反应: %s")

T_("%s:%d: maximum data length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka dat (%d B)")
deDE("%s:%d: Maximale Datenlänge überschritten (%d B)")
fiFI("%s:%d: datan enimmäispituus ylitetty (%d B)")
frFR("%s:%d : dépassement de la longueur maximale des données (%d O)")
huHU("%s:%d: maximális adathossz túllépése (%d B)")
itIT("")
plPL("%s:%d: przekroczono dopuszczalny rozmiar danych (%d B)")
ruRU("%s:%d: превышен максимальный размер данных "
     "(%d B)")
srSP("")
trTR("%s:%d: maksimum veri boyutu aşıldı (%d B)")
zhCN("%s:%d: 超出了最大数据长度(%d B)")

T_("%s:%d: maximum header length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka hlaviček (%d B)")
deDE("%s:%d: Maximale Headerlänge überschritten (%d B)")
fiFI("%s:%d: headerin enimmäispituus ylitetty (%d B)")
frFR("%s:%d : dépassement de la longueur maximale de l'en-tête (%d O)")
huHU("%s:%d: maximális fejléchossz túllépése (%d B)")
itIT("")
plPL("%s:%d: przekroczono dopuszczalną długość nagłówka (%d B)")
ruRU("%s:%d: превышен максимальный размер заголовка "
     "(%d B)")
srSP("")
trTR("%s:%d:Maksimum üstbilgi boyutu aşıldı (%d B)")
zhCN("%s:%d: 超出了最大头长度(%d B)")

T_("%s:%d: timed out when receiving server response")
csCZ("%s:%d: vypršel časový limit při načítání odpovědi")
deDE("%s:%d: Timeout beim Empfang der Serverantwort")
fiFI("%s:%d: palvelinvastineen vastaanotto aikakatkaistu")
frFR("%s%d : temps dépassé à la réception de la réponse du serveur")
huHU("%s:%d: időtúllépés a kiszolgáló válaszára várva")
itIT("")
plPL("%s:%d: przekroczono czas oczekiwania na odpowiedź serwera")
ruRU("%s:%d: таймаут при приёме ответа от сервера")
srSP("")
trTR("%s:%d: Sunucudan  yanıt beklenirken zaman aşımı meydana geldi")
zhCN("%s:%d: 接收服务器反应时超时")

T_("Maximum content size exceeded: %d")
csCZ("Překročena maximální povolená délka datového obsahu: %d")
deDE("Maximaler Datenumfang überschritten: %d")
fiFI("Sisällön enimmäiskoko ylitetty: %d")
frFR("")
huHU("A maximális tartalomhossz túllépve: %d")
itIT("")
plPL("Przekroczono dopuszczalny rozmiar zawartości: %d")
ruRU("Превышен максимальный размер содержимого: "
     "%d")
srSP("")
trTR("Maksimum içerik boyutu aşıldı: %d")
zhCN("最大内容长度超出:%d")

T_("Partial input: %d out of %d")
csCZ("Přijata neúplná data: %d z %d")
deDE("Unvollständiger Empfang: %d von %d")
fiFI("Osittainen syöte: %d / %d")
frFR("Saisie partielle : %d de %d")
huHU("Részleges beolvasás: %d a %d-ból")
itIT("")
plPL("Dane częściowe: %d z %d")
ruRU("Частичный ввод: %d из %d")
srSP("")
trTR("Kısmi girdi: %d/%d")
zhCN("部分输入: %d out of %d")


// smtp.cpp

T_("Communication Failure: Timeout.")
csCZ("Porucha komunikace: vypršel časový limit.")
deDE("")
fiFI("Viestintävirhe: Aikakatkaisu.")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Bağlantı başarısız: Zaman aşımı.")
zhCN("")

T_("Error writing data to socket: communication port closed.")
csCZ("Chyba při zápisu dat do socketu: komunikační kanál byl uzavřen.")
deDE("")
fiFI("Virhe socketiin kirjoitettaessa: kommunikointiportti suljettu.")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Sokete yazma hatası: bağlantı kesildi.")
zhCN("")

T_("Error writing data to socket, error code: ")
csCZ("Chyba při zápisu dat do socketu, kód chyby: ")
deDE("")
fiFI("Virhe socketiin kirjoitettaessa, virhe koodi: ")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Sokete yazma hatası meydana geldi. Hata kodu: ")
zhCN("")

T_("Error reading data from socket: commuication port closed.")
csCZ("Chyba při čtení dat ze socketu: komunikační kanál byl uzavřen.")
deDE("")
fiFI("Virhe socketista luettaessa: kommunikointiportti suljettu.")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Soket okuma hatası: bağlantı kesildi.")
zhCN("")

T_("Host not set.")
csCZ("Hostitel není zadán.")
deDE("")
fiFI("Isäntää ei ole asetettu.")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Host hazır değil.")
zhCN("")

T_("Recipient not set.")
csCZ("Není zadán příjemce.")
deDE("")
fiFI("Vastaanottajaa ei ole asetettu.")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Alıcı hazır değil.")
zhCN("")


// sproc.cpp

T_("pipe() error; error code = %d")
csCZ("chyba pipe(); kód chyby = %d")
deDE("pipe()-Fehler; Fehlercode = %d")
fiFI("pipe() virhe; virhe koodi = %d")
frFR("erreur pipe(); code d'erreur = %d")
huHU("pipe() hiba; hibakód = %d")
itIT("")
plPL("błąd pipe(); kod błędu = %d")
ruRU("ошибка pipe(); код ошибки = %d")
srSP("")
trTR("pipe() hatası; hata kodu = %d")
zhCN("pipe() error; error code = %d")

T_("fork() error; error code = %d")
csCZ("chyba fork(); kód chyby = %d")
deDE("fork()-Fehler; Fehlercode = %d")
fiFI("fork() virhe; virhe koodi = %d")
frFR("erreur fork(); code d'erreur = %d")
huHU("fork() hiba; hibakód = %d")
itIT("")
plPL("błąd fork(); kod błędu = %d")
ruRU("ошибка fork(); код ошибки = %d")
srSP("")
trTR("fork() hatası; hata kodu = %d")
zhCN("fork() error; error code = %d")

T_("Opening host '%s' / port %d failed, error = %s")
csCZ("Připojování k hostiteli '%s' / port %d selhalo, chyba = %s")
deDE("Zugriff auf den Host '%s' / port %d fehlgeschlagen, Fehler = %s")
fiFI("Kytkentä isäntään '%s' / portti %d epäonnistui, virhe = %s")
frFR("Erreur d'ouverture de '%s' / port %d, erreur = %s")
huHU("A '%s' gép / %d port megnyitása sikertelen, hiba = %s")
itIT("")
plPL("Łączenie z hostem '%s' / port %d nie powiodło się, błąd = %s")
ruRU("Подсоединение к хосту '%s' / порту %d не удачно, "
     "ошибка = %s")
srSP("")
trTR("'%s' hostuna '%d' portundan bağlanma girişi başarısız oldu. Hata "
     "= %s")
zhCN("Opening host '%s' / port %d failed, error = %s")

T_("Error running process: %s\nCommand: %s")
csCZ("Chyba při spouštění procesu: %s\nPříkaz: %s")
deDE("Fehler beim Ausführen des Prozesses: %s\nBefehl: %s")
fiFI("Virhe prosessin suorittamisessa: %s\nCommand: %s")
frFR("Erreur d'exécution du programme : %s\nCommande : %s")
huHU("Hiba a %s folyamat\n%s parancs futtatásánál")
itIT("")
plPL("Błąd uruchamiania procesu: %s\nKomenda: %s")
ruRU("Ошибка при запуске процесса: %s\nКоманда: "
     "%s")
srSP("")
trTR("'%s' işleminin çalıştırılması sırasında hata oluştu\nKomut: "
     "%s")
zhCN("运行进城错误:%s\n命令: %s")

T_("Communication error; process = %s")
csCZ("Chyba spojení; proces = %s")
deDE("Kommunikationsfehler; Prozess = %s")
fiFI("Kommunikointi virhe; prosessi = %s")
frFR("Erreur de communication ; processus = %s")
huHU("Kommunikációs hiba; folyamat = %s")
itIT("")
plPL("Błąd komunikacji; proces = %s")
ruRU("Ошибка коммуникации; процесс = %s")
srSP("")
trTR("İletişim hatası; işlem = %s")
zhCN("通信错误; 进城 = %s")

T_("Missing command line (host = %s).")
csCZ("Chybí příkazová řádka (hostitel = %s).")
deDE("Fehlende Befehlszeile (Host = %s)")
fiFI("Puuttuva komentorivi (isäntä = %s).")
frFR("Ligne de commande manquante (hôte = %s).")
huHU("Hiányzó parancssor (gép = %s)")
itIT("")
plPL("Brak linii poleceń (host = %s).")
ruRU("Не указана командная строка (хост = %s)")
srSP("")
trTR("Eksik komut satırı (Host = %s).")
zhCN("缺少命令行(主机 = %s).")


// Obsolete

T_("Cannot open socket %s:%d: %s")
csCZ("Nelze otevřít socket %s:%d: %s")
deDE("")
fiFI("Socketia ei voi avata %s:%d: %s")
frFR("")
huHU("")
itIT("")
plPL("")
ruRU("")
srSP("")
trTR("Hata: Soket açılamadı. %s:%d: %s")
zhCN("")
