TABLE_(PERSON)
	INT_    (ID)      PRIMARY_KEY AUTO_INCREMENT
	STRING_ (FIRSTNAME, 200)
	STRING_ (LASTNAME, 200)
	STRING_ (EMAIL, 200)
	STRING_ (SEX, 1)
END_TABLE

TABLE_(SES)
	STRING  (ID, 100) PRIMARY_KEY
	BLOB    (DATA)
	TIME    (LASTWRITE)
END_TABLE